<?php
return array(
	#Äëÿ øàáëîíà Eleanor BB Editor, êîòîğûé íàõîäèòñÿ â ôàéëå /templates/Audora/BBeditor.php
	'preview'=>'Ïğåäïğîñìîòğ',
	'increase_field'=>'Óâåëè÷èòü ïîëå',
	'decrease_field'=>'Óìåíüøèòü ïîëå',
	'bold'=>'Ïîëóæèğíûé (Ctrl+B)',
	'italic'=>'Êóğñèâ (Ctrl+I)',
	'underline'=>'Ïîä÷åğêíóòûé (Ctrl+U)',
	'strike'=>'Çà÷åğêíóòûé (Ctrl+Shift+S)',
	'left'=>'Ñëåâà (Ctrl+Shift+L)',
	'center'=>'Ïî öåíòğó (Ctrl+Shift+M)',
	'right'=>'Ñïğàâà (Ctrl+Shift+R)',
	'justify'=>'Ïî îáîèì êğàÿì (Ctrl+Shift+J)',
	'hr'=>'Ãîğèçîíòàëüíàÿ ëèíèÿ (Ctrl+H)',
	'link'=>'Âñòàâêà ññûëêè (Ctrl+L)',
	'email'=>'Âñòàâêà E-mail (Ctrl+E)',
	'image'=>'Âñòàâêà êàğòèíêè (Ctrl+Shift+I)',
	'ul'=>'Ìàğêèğîâàííûé ñïèñîê',
	'ol'=>'Íóìåğîâàííûé ñïèñîê',
	'li'=>'Ñòğîêà ñïèñêà',
	'nobb'=>'Áåç BB êîäîâ',
	'tm'=>'Òîğãîâàÿ ìàğêà',
	'copyright'=>'Êîïèğàéò',
	'registered'=>'Çàğåãèñòğèğîâàííûé',
	'font'=>'Øğèôò',
	'color'=>'Öâåò',
	'select'=>'Âûáğàòü',
	'background'=>'Ôîí',
	'size'=>'Ğàçìåğ',
	'tab'=>'Tab',
);