<?php
return array(
	#For template Eleanor BB Editor, located in file /templates/*/BBeditor.php
	'preview'=>'Preview',
	'increase_field'=>'Increase Field',
	'decrease_field'=>'Decrease field',
	'bold'=>'Bold (Ctrl+B)',
	'italic'=>'Italics (Ctrl+I)',
	'underline'=>'Underline (Ctrl+U)',
	'strike'=>'Strike (Ctrl+Shift+S)',
	'left'=>'Left (Ctrl+Shift+L)',
	'center'=>'Center (Ctrl+Shift+M)',
	'right'=>'Right (Ctrl+Shift+R)',
	'justify'=>'On both sides (Ctrl+Shift+J)',
	'code'=>'Code (Ctrl+Shift+C)',
	'quote'=>'Quote (Ctrl+Q)',
	'hr'=>'Horizontal line (Ctrl+H)',
	'link'=>'Reference insert (Ctrl+L)',
	'email'=>'E-mail insert (Ctrl+E)',
	'image'=>'Picture insert (Ctrl+Shift+I)',
	'ul'=>'Bulleted list',
	'ol'=>'Numbered list',
	'li'=>'String list',
	'nobb'=>'Without BB codes',
	'tm'=>'Trade mark',
	'copyright'=>'Copyright',
	'registered'=>'Logged',
	'font'=>'Font',
	'color'=>'Color',
	'select'=>'Choose',
	'background'=>'Background',
	'size'=>'Size',
	'tab'=>'Tab',
);