<?php
return array(
	#Äëÿ øàáëîíó Eleanor BB Editor, ùî çíàõîäèòüñÿ ó ôàéë³ /templates/*/BBeditor.php
	'preview'=>'Ïîïåğåäí³é ïåğåãëÿä',
	'increase_field'=>'Çá³ëüøèòè ïîëå',
	'decrease_field'=>'Çìåíøèòè ïîëå',
	'bold'=>'Íàï³âæèğíèé (Ctrl+B)',
	'italic'=>'Êóğñèâ (Ctrl+I)',
	'underline'=>'Ï³äêğåñëåíèé (Ctrl+U)',
	'strike'=>'Çàêğåñëåíèé (Ctrl+Shift+S)',
	'left'=>'Çë³âà (Ctrl+Shift+L)',
	'center'=>'Ïî öåíòğó (Ctrl+Shift+M)',
	'right'=>'Ñïğàâà (Ctrl+Shift+R)',
	'justify'=>'Ïî îáîõ êğàÿõ (Ctrl+Shift+J)',
	'hr'=>'Ãîğèçîíòàëüíà ë³í³ÿ (Ctrl+H)',
	'link'=>'Âñòàâêà ïîñèëàííÿ (Ctrl+L)',
	'email'=>'Âñòàâêà E-mail (Ctrl+E)',
	'image'=>'Âñòàâêà çîáğàæåííÿ (Ctrl+Shift+I)',
	'ul'=>'Ìàğêîâàíèé ñïèñîê',
	'ol'=>'Íóìåğîâàíèé ñïèñîê',
	'li'=>'Ğÿäîê ñïèñêó',
	'nobb'=>'Áåç BB êîä³â',
	'tm'=>'Òîğãîâà ìàğêà',
	'copyright'=>'Êîï³ğàéò',
	'registered'=>'Çàğåºñòğîâàíèé',
	'font'=>'Øğèôò',
	'color'=>'Êîë³ğ',
	'select'=>'Âèáğàòè',
	'background'=>'Ôîí',
	'size'=>'Ğîçì³ğ',
	'tab'=>'Tab',
);