<?php
return array(
	'sessm'=>'Service management',
	'sessm_'=>'Your website services settings',
	'modm'=>'Modules management',
	'modm_'=>'Your website modules-expansions settings',
	'blokm'=>'Blocks management',
	'blokm_'=>'Your website blocks management',
	'grm'=>'Users groups',
	'grm_'=>'Users groups and their rights settings',
	'userm'=>'Users management',
	'userm_'=>'Edit, delete, block',
	'smm'=>'Smiles management',
	'smm_'=>'Add, delete or edit code',
	'smg'=>'Site map generator',
	'smg_'=>'For all website pages been indexiteв by search rngines',
	'db'=>'Data base',
	'db_'=>'Backup and recovery, repair and optimization',
	'tmpe'=>'Templates editor',
	'tmpm_'=>'Copy or edit templates',
	'ownb'=>'Own BB codes',
	'ownb_'=>'Own BB codes management',
	'comm'=>'Comments management',
	'comm_'=>'Comments reading anв editing',
	'tasks'=>'Task manager',
	'tasks_'=>'Automatic task loader by schedule',
	'spam'=>'Subscribe by email',
	'spam_'=>'Send e-mails for users',
	'installer'=>'Addons installer',
	'installer_'=>'Install addons for system',
	'multisite'=>'Miltisite',
	'multisite_'=>'Settings autologin for users between your sites',
);