<?php
return array(
	#For /addons/admin/modules/user_groups.php, /addons/admin/modules/users.php
	'base_o'=>'Basic options',
	'g_name'=>'Group name',
	'html_pref'=>'HTML prefix group',
	'html_pref_'=>'Example: &lt;span style="color:red"&gt;&lt;b&gt;',
	'html_suf'=>'HTML suffix groups',
	'html_suf_'=>'Example: &lt;/b&gt;&lt;/span&gt;',
	'descr'=>'Description',
	'global_r'=>'Global rights',
	'aa'=>'Access to the panel administrator',
	'are_you_sure'=>'Are you sure?',
	'ban'=>'Banned?',
	'ban_'=>'Users of this group would be banned.',
	'captcha'=>'Display captcha?',
	'captcha_'=>'Display special images on which the user needs to read the inscription, thus proving that he is not a bot.',
	'moderate'=>'Enable moderation publications user?',
	'moderate_'=>'If you enable this option, all user-added materials (eg, news) will take place moderated.',
	'cls'=>'Open access to the closed site?',
	'limits'=>'Limits',
	'flood_limit'=>'Flood limit',
	'flood_limit_'=>'The temporary restriction between the publication of communications or content. Is in seconds.',
	'search_limit'=>'Search limit ',
	'search_limit_'=>'The temporary restriction between attempts to search. Is in seconds.',
	'max_size'=>'Maximum size of uploaded files (in KB):',
	'max_size_'=>'1 - no limits;<br /> 0 - prohibit the uploading of files',
	'delc'=>'Confirm delete',
	'notitle'=>function($l){return'Please, fill group name'.($l ? ' (for '.$l.')' : '');},
	'list'=>'List of groups',
	'adding'=>'Adding group',
	'editing'=>'Editing group',
);