<?php
return array(
	#For /addons/admin/modules/section_general.php
	'server_info'=>'Server Information',
	'logs'=>'Logs',
	'viewing_log'=>'Viewing log file  &quot;&s&quot;',
	'log_error'=>'Log error code',
	'log_except'=>'Log exception',
	'log_esite'=>'Error log on the site',
	'log_db'=>'Log errors DB',
	'license_'=>'License and sanctions',

	#For template
	'install_nd'=>'Install folder is still not deleted! For security reasons, it should be removed as soon as possible.',
	'thanks'=>'Thank you for choosing Eleanor CMS!',
	'thanks_'=>'We hope that with the help of CMS Eleanor, you can create a successful website. System capabilities are not limited! In this you can see by visiting our <a href="http://eleanor-cms.ru/store/" target="_blank">shop</a>. For help you can visit the <a href="http://eleanor-cms.ru/forum/" target="_blank">forum</a>. About the identified error is reported in the <a href="http://eleanor-cms.ru/bugtracker/" target="_blank">bugtracker</a> project. The latest version of Eleanor CMS you can always download from <a href="http://eleanor-cms.ru/" target="_blank">official site</a> in section <a href="http://eleanor-cms.ru/download/" target="_blank">download</a>.<br />You can also <a href="http://eleanor-cms.ru/donate/" target="_blank">donate Eleanor CMS project</a>.<br /><br />Sincerely, developers Eleanor CMS.',
	'name'=>'Username',
	'group'=>'Group',
	'lastw'=>'Last visit',
	'reg'=>'Registered',
	'crbl'=>'Create block',
	'crnews'=>'Create news',
	'crpage'=>'Create page',
	'crspam'=>'Create newsletter',
	'crmenu'=>'Create menu item',
	'cruser'=>'New users',
	'stat'=>'Statistics',
	'comments'=>'Last comments',
	'users'=>'Users',
	'newselc'=>'News Eleanor CMS',
	'ownnote'=>'Personal notebook',
	'gennote'=>'Public notebook',
	'stcomm'=>'Number of comments this week (total):',
	'stuser'=>'Number of registered users this week (total):',
	'stsite'=>'Number of days to which live site:',
	'time_on_server'=>'Time on the server: ',
	'cachem'=>'Managing cache',
	'cache_'=>'Much in system cached: For example, you change the category name changes on the site not happened? So categories are in cache. To resolve this problem, use this function.',
	'cache_deleted'=>'Cache removed!',
	'cachedel'=>'Delete cache',
	'get_value'=>'Get value',
	'file'=>'File',
	'path'=>'Path',
	'size'=>'Size',
	'view_log'=>'View log',
	'download_log'=>'Download log',
	'delete_log'=>'Delete log',
	'nologs'=>'Logs no. The site is fine',
	'logs_size'=>'The volume of logs folder: ',
	'empty'=>'empty',
	'license'=>'License',
	'sanctions'=>'Sanctions',
	'print'=>'Printable version',
);