<?php
return array(
	#For /addons/admin/modules/spam.php
	'delc'=>'Confirm delete',
	'list'=>'Mailing list',
	'editing'=>'Editing mailing',
	'adding'=>'Creating mailing',
	'empty_innertitle'=>function($l){return'Internal title can not be empty'.($l ? ' (for '.$l.')' : '');},

	#For template
	'runned'=>'This mailing has been started. Some fields are protected from editing.',
	'username'=>'Username',
	'groups'=>'Groups',
	'last_visit'=>'Last visit',
	'nousers'=>'No users relevant search terms',
	'condition'=>'Condition',
	'nospam'=>'Mailing is not detected',
	'stop'=>'Stop',
	'stopped'=>'Stopped',
	'pause'=>'Pause',
	'paused'=>'Paused',
	'run'=>'Run',
	'finished'=>'Finished',
	'+run'=>'Restart',
	'spampp'=>'Mailings per page: %s',
	'userfilter'=>'User filter',
	'and'=>' AND',
	'or'=>' OR',
	'b'=>'Begins with',
	'e'=>'Ends on',
	'c'=>'Contains',
	'm'=>'Coincides with',
	'register'=>'Register',
	'gender'=>'Gender',
	'ni'=>'Not important',
	'ns'=>'Not defined',
	'female'=>'Female',
	'male'=>'Male',
	'ts'=>'Test search',
	'hideres'=>'Hide results',
	'ssetting'=>'Sending email settings',
	'per_run'=>'Number of letters',
	'per_run_'=>'Number of letters sent at once',
	'delspam'=>'Remove mailling',
	'delspam_'=>'on complete',
	'innertitle'=>'Internal title',
	'topic'=>'Subject',
	'text'=>'Text',
	'add'=>'Create a mailing',
	'deleting'=>'Do you really want to delete the mailing list &quot;%s&quot;?',
);