<?php
return array(
	#For /addons/admin/modules/users.php
	'personal'=>'Personal',
	'gender'=>'Gender',
	'nogender'=>'Unknown',
	'male'=>'Male',
	'female'=>'Female',
	'bio'=>'Biography',
	'interests'=>'Interests',
	'location'=>'Location',
	'site'=>'Site',
	'site_'=>'Enter a website address, beginning with http://',
	'signature'=>'Signature',
	'connect'=>'Communications',
	'vk'=>'VK',
	'vk_'=>'Please enter only your id, or name',
	'twitter_'=>'Please enter nickname only',
	'theme'=>'Template',
	'by_default'=>'Default',
	'editor'=>'Editor',
	'lettertitle'=>'Email subject',
	'letterdescr'=>'Email text',
	'letter4new'=>'Email to create a new user',
	'descr4new'=>'{site} - site name<br />
{name} - user name<br />
{login} - user login<br />
{pass} - user password<br />
{link} - link to your site',
	'letter4name'=>'Email to changing user name',
	'descr4name'=>'{site} - site name<br />
{name} - user login<br />
{oldlogin} - old user login<br />
{newlogin} - new user login<br />
{link} - link to your site',
	'letter4pass'=>'Email when the password changed',
	'letters'=>'Letters formats',
	'whoonline'=>'Who online',
	'delc'=>'Confirm delete',
	'adding'=>'Creating user',
	'editing'=>'Editing user',
	'list'=>'Users list',

	#Errors
	'SITE_ERROR'=>'Site address is entered incorrectly',
	'SHORT_ICQ'=>'ICQ number must contain at least 5 digits',
	'ERROR_BANDATE'=>'Incorrectly entered the date of the user blocking',
	'PASSWORD_MISMATCH'=>'Password mismatch',
	'AVATAR_NOT_EXISTS'=>'Chosen avatar does not exist',
	'EMPTY_NAME'=>'Username is empty',
	'EMAIL_ERROR'=>'Entered e-mail in incorrect',
	'EMPTY_PASSWORD'=>'Password not entered',
	'NAME_EXISTS'=>'This user name already exists',
	'EMAIL_EXISTS'=>'This e-mail already exists',
	'EMPTY_EMAIL'=>'E-mail not entered',
	'NAME_TOO_LONG'=>'User name length should not exceed %s characters. Your - %s characters.',
	'PASS_TOO_SHORT'=>'The password should be at least %s characters. Your - %s characters.',

	#For template /template/*/Classes/UsersOnline.php
	'user_info'=>'Information about the visitor',
	'users'=>function($n){return $n.($n>1 ? ' users' : ' user');},
	'min_left'=>function($n){return $n.($n>1 ? ' minutes ago' : ' minute ago');},
	'bots'=>function($n){return $n.' search '.($n>1 ? 'bots' : 'bot');},
	'guests'=>function($n){return $n.($n>1 ? ' guests' : ' guest');},
	'activity'=>'Activity',
	'now_onp'=>'Now on page',
	'f'=>'Referrer',
	'browser'=>'Browser',
	'service'=>'Сервис',
	'c'=>'Supporting charsets',
	'e'=>'Supported data types',
	'ips'=>'Addons IPs',
	'session_nf'=>'Session not found',
	'go'=>'Go',

	#For template /template/*/Classes/Users.php
	'add'=>'Create user',
	'not_imp'=>'-No matter-',
	'begins'=>'Begins with',
	'contains'=>'Contains',
	'match'=>'Matches',
	'endings'=>'Ends with',
	'name'=>'User name',
	'fullname'=>'Full name',
	'group'=>'Group',
	'agroups'=>'Others groups',
	'last_visit'=>'Last visit',
	'register'=>'Registered',
	'from-to'=>'from - to YYYY-MM-DD HH:MM:SS',
	'unf'=>'Users not found',
	'upp'=>'Users per page: %s',
	'deleting'=>'Do you really want to delete the user <b>%s</b> (%s)?',
	'lap'=>'Login and password',
	'general'=>'General',
	'extra'=>'Private',
	'special'=>'Special',
	'block'=>'Blocking',
	'statistics'=>'Statistics',
	'pass'=>'Password',
	'passc'=>'Confirm password',
	'pass_'=>'You may leave password field empty - system will automatically generate password',
	'slname'=>'Inform about change of name',
	'slname_'=>'The user will receive a message with information about the new name',
	'slpass'=>'Informed about changing password',
	'slpass_'=>'The user will receive a message with the new password',
	'slnew'=>'Inform about creating an account',
	'slnew_'=>'The user will receive a message with information about his new account on your site',
	'account'=>'Account',
	'lang'=>'Language',
	'timezone'=>'Timezone',
	'inherit'=>'Inherit',
	'addo'=>'Add',
	'replace'=>'Replace',
	'ban-to'=>'Ban for',
	'ban-exp'=>'Ban explain',
	'fla'=>'Failed authentication attempts',
	'clean'=>'Clean',
	'avatar'=>'Avatar',
	'alocation'=>'Location',
	'apersonal'=>'Upload',
	'agallery'=>'From gallery',
	'amanage'=>'Manage',
	'gallery_select'=>'Select',
	'noavatar'=>'No avatar',
	'sessions'=>'Opened user\'s sessions',
	'find'=>'find',
	'staticip'=>'Static IP address',
	'staticip_'=>'Enabling this option is recommended for users with a static IP address. When enabled, the authentication cookie is attached to an IP address, making it impossible to steal cookies.',
	'awo'=>'all, who online',
	'alls'=>'all',
	'allg'=>'all, who was here',
	'sshow'=>'Show',
	'who'=>'Who',
	'ets'=>'Entry to site',
	'pl'=>'Location on site',
	'guest'=>'Guest',
	'expire'=>'Expire %s',
	'expired'=>'Expired %s',
	'spp'=>'Sessions per page: %s',
	'no_avatars'=>'No available avatars',
	'cancel_avatar'=>'Cancel',
	'togals'=>'Galleries',
	'datee'=>'Expiration date',
	'csnd'=>'You can not delete current session',

	#External auth
	'twitter.com'=>'Twitter',
	'www.facebook.com'=>'Facebook',
	'openid.yandex.ru/server'=>'Yandex',
	'vkontakte.ru'=>'VK',
);