<?php
return array(
	#Для BBeditor.php
	'preview'=>'Попередній перегляд',
	'increase_field'=>'Збільшити поле',
	'decrease_field'=>'Зменшити поле',
	'bold'=>'Напівжирний (Ctrl+B)',
	'italic'=>'Курсив (Ctrl+I)',
	'underline'=>'Підкреслений (Ctrl+U)',
	'strike'=>'Закреслений (Ctrl+Shift+S)',
	'left'=>'Зліва (Ctrl+Shift+L)',
	'center'=>'По центру (Ctrl+Shift+M)',
	'right'=>'Справа (Ctrl+Shift+R)',
	'justify'=>'По обох краях (Ctrl+Shift+J)',
	'hr'=>'Горизонтальна лінія (Ctrl+H)',
	'link'=>'Вставка посилання (Ctrl+L)',
	'email'=>'Вставка E-mail (Ctrl+E)',
	'image'=>'Вставка зображення (Ctrl+Shift+I)',
	'ul'=>'Маркований список',
	'ol'=>'Нумерований список',
	'li'=>'Рядок списку',
	'nobb'=>'Без BB кодів',
	'tm'=>'Торгова марка',
	'copyright'=>'Копірайт',
	'registered'=>'Зареєстрований',
	'font'=>'Шрифт',
	'color'=>'Колір',
	'select'=>'Вибрати',
	'background'=>'Фон',
	'size'=>'Розмір',
	'tab'=>'Tab',
);