<?php
return array(
	#Для BBeditor.php
	'preview'=>'Предпросмотр',
	'increase_field'=>'Увеличить поле',
	'decrease_field'=>'Уменьшить поле',
	'bold'=>'Полужирный (Ctrl+B)',
	'italic'=>'Курсив (Ctrl+I)',
	'underline'=>'Подчеркнутый (Ctrl+U)',
	'strike'=>'Зачеркнутый (Ctrl+Shift+S)',
	'left'=>'Слева (Ctrl+Shift+L)',
	'center'=>'По центру (Ctrl+Shift+M)',
	'right'=>'Справа (Ctrl+Shift+R)',
	'justify'=>'По обоим краям (Ctrl+Shift+J)',
	'hr'=>'Горизонтальная линия (Ctrl+H)',
	'link'=>'Вставка ссылки (Ctrl+L)',
	'email'=>'Вставка E-mail (Ctrl+E)',
	'image'=>'Вставка картинки (Ctrl+Shift+I)',
	'ul'=>'Маркированный список',
	'ol'=>'Нумерованный список',
	'li'=>'Строка списка',
	'nobb'=>'Без BB кодов',
	'tm'=>'Торговая марка',
	'copyright'=>'Копирайт',
	'registered'=>'Зарегистрированный',
	'font'=>'Шрифт',
	'color'=>'Цвет',
	'select'=>'Выбрать',
	'background'=>'Фон',
	'size'=>'Размер',
	'tab'=>'Tab',
);