<?php
return array(
	'no'=>'no',
	'yes'=>'yes',
	'all'=>'all',
	'update'=>'Refresh',
	'alls'=>'All sessions',
	'loading'=>'Loading...',
	'edit_menu'=>'Edit menu',
	'pages'=>'Pages:',
	'main_m'=>'Main features',
	'extra_m'=>'Additional features',
	'select_user'=>'Choose a user',
	'warning'=>'Warning',
	'error'=>'Mistake',
	'errors'=>'Mistakes',
	'info'=>'Information',
	'sversion'=>'Version system:',
	'view site'=>'View site',
	'msjump'=>'-Jump to-',
	'goto_page'=>'Go to page',
	'navigation'=>'Navigation',
	'goback'=>'Back',
	'exit'=>'Logout',
	'edit'=>'Edit',
	'functs'=>'Functions',
	'delete'=>'Remove',
	'name'=>'Name',
	'title'=>'Title',
	'descr'=>'Description',
	'activate'=>'Activate',
	'deactivate'=>'Deactivate',
	'are_you_sure'=>'Are you sure?',
	'with_selected'=>'On the point: ',
	'waiting_act'=>'Pending Activation',
	'inactive'=>'Inactive',
	'active'=>'Active',
	'general'=>'General',
	'for_all_langs'=>'For all languages',
	'apply'=>'Apply',
	'set_for_langs'=>'Set for languages',
	'nodraft'=>'Without draft',
	'filters'=>'Filters',
	'moveup'=>'Move up',
	'movedown'=>'Move down',

	#Äëÿ Enter.php
	'login'=>'Login:',
	'pass'=>'Password:',
	'enter'=>'Enter',

	#For Editor.php
	'smiles'=>'Smilies',
);