<?php
return array(
	#For classes/General.php
	'thanks'=>'Thank you!',
	'thanks_'=>'We hope that with the help of Eleanor CMS you can create a successful website. If you have any difficulties, please visit <a href="http://eleanor-cms.ru/forum/" target="_blank">forum</a> for get help, on revealed errors report to the <a href="http://eleanor-cms.ru/bugtracker/" target="_blank">bug tracker</a>, join us on <a href="http://eleanor-cms.ru/social/" target="_blank">social networks</a>, fill the <a href="http://eleanor-cms.ru/wiki/" target="_blank">wiki/a>, and <a href="http://eleanor-cms.ru/download/" target="_blank">download</a> the latest version of the <a href="http://eleanor-cms.ru/" target="_blank">official site</a>. To contact developers, please use the <a href="http://eleanor-cms.ru/contacts/" target="_blank">feedback form</a>. Please <a href="http://eleanor-cms.ru/donate/" target="_blank">donate</a> the project Eleanor CMS, because it just kept on our enthusiasm.<br /><br />Sincerely, developers Eleanor CMS.',
	'install_nd'=>'Install folder is still not deleted! For security reasons, it should be removed as soon as possible.',
	'name'=>'Username',
	'group'=>'Group',
	'lastw'=>'Last visit',
	'reg'=>'Registered',
	'crbl'=>'Create block',
	'crnews'=>'Create news',
	'crpage'=>'Create page',
	'crspam'=>'Create newsletter',
	'crmenu'=>'Create menu item',
	'cruser'=>'New users',
	'stat'=>'Statistics',
	'comments'=>'Last comments',
	'users'=>'Users',
	'newselc'=>'News Eleanor CMS',
	'ownnote'=>'Personal notebook',
	'gennote'=>'Public notebook',
	'stcomm'=>'Number of comments this week (total):',
	'stuser'=>'Number of registered users this week (total):',
	'stsite'=>'Number of days to which live site:',
	'time_on_server'=>'Time on the server: ',
	'cachem'=>'Managing cache',
	'cache_'=>'Much in system cached: For example, you change the category name changes on the site not happened? So categories are in cache. To resolve this problem, use this function.',
	'cache_deleted'=>'Cache removed!',
	'cachedel'=>'Delete cache',
	'get_value'=>'Get value',
	'file'=>'File',
	'path'=>'Path',
	'size'=>'Size',
	'view_log'=>'View log',
	'download_log'=>'Download log',
	'delete_log'=>'Delete log',
	'nologs'=>'Logs no. The site is fine',
	'empty'=>'empty',
	'license'=>'License',
	'sanctions'=>'Sanctions',
	'print'=>'Printable version',
	'fixed'=>'Fixed',
);