<?php
return array(
	#For Classes/Sitemap.php
	'NOFILE'=>'File not specified',
	'NO_NEXT_RUN'=>'For a given run time, the task never runs',
	'NOMODULES'=>'No modules selected',
	'add'=>'Add sitemap',
	'save'=>'Save sitemap',
	'editrobots'=>'Edit robots.txt',
	'file'=>'File',
	'file_'=>'Relatively to site root. Without extension.',
	'status'=>'Status',
	'pnrun'=>'Previous and next run',
	'nosm'=>'Sitemaps not found',
	'smpp'=>'Sitemaps per page: %s',
	'egzip'=>'Enable GZIP',
	'fullurl'=>'Full URL',
	'per_run'=>'The number of links that are generated at a time',
	'sendservice'=>'Alert services',
	'runnow'=>'Run now',
	'recreate'=>'Recreate file',
	'runyear'=>'Years',
	'runyear_'=>'Specify the years in which to run the generating sitemap. Enter * to run each year. For example: '.date('Y').','.date('Y',strtotime('+1year')),
	'runmonth'=>'Months',
	'runmonth_'=>'Specify the months in which to start the task. Enter * to run each month. For example: '.date('m').','.date('m',strtotime('+1month')),
	'runday'=>'Days',
	'runday_'=>'Specify the days of the month in which to start the task. Enter * to run every day. For example: '.date('d').','.date('d',strtotime('+7day')),
	'runhour'=>'Hours',
	'runhour_'=>'Specify the hours that you need to run the generating sitemap. Enter * to run every hour. For example: '.date('H').','.date('H',strtotime('+2hour')),
	'runminute'=>'Minutes',
	'runminute_'=>'Specify the minutes when you need to run the generating sitemap. Enter * to run every minute. For example: '.date('i').','.date('i',strtotime('+1min')),
	'runsecond'=>'Seconds',
	'runsecond_'=>'Specify the seconds, that need to run the generating sitemap. Enter * to run every second. For example: 14,12',
	'timetorun'=>'Run time',
	'mopts'=>'Options of modules',
	'nomops'=>'No options of modules',
	'robots'=>'Contents of robots.txt',
	'rsaved'=>'Contents of robots.txt successfully saved',
	'deleting'=>'Do you really want to delete the sitemap &quot;%s&quot;? Файл &quot;%s&quot; так же будет удален.',
);