<?php
return array(
	#Для Classes/Uploader.php
	'add_folder'=>'Создать папку',
	'open_folder'=>'Открыть папку',
	'insert_file'=>'Вставить в редактор (+ALT - диалог)',
	'insert_attach'=>'Вставить как объект (+ALT - диалог)',
	'open_file'=>'Открыть файл',
	'go_up'=>'На один уровень вверх',
	'cancel_upload'=>'Отменить загрузку',
	'upload_file'=>'Загрузить файл',
	'loading'=>'Загрузка...',
	'rename'=>'Переименовать',
	'show'=>'Показать',
	'hide'=>'Скрыть',
	'showprevs'=>'Отображать превьюшки',
	'doprevs'=>'Создавать превьюшки',
	'watermark'=>'Watermark',
	'create_file'=>'Создать файл',
	'save'=>'Сохранить',
	'cancel'=>'Отменить',
	'edit'=>'Править',
	'update'=>'Обновить',
	'delete'=>'Удалить',
);