<?php
return array(
	#Для Classes/Uploader.php
	'add_folder'=>'Створити папку',
	'open_folder'=>'Відкрити папку',
	'insert_file'=>'Вставити у редактор (+ALT - діалог)',
	'insert_attach'=>'Вставити як об\'єкт (+ALT - діалог)',
	'open_file'=>'Відкрити файл',
	'go_up'=>'На один рівень вгору',
	'cancel_upload'=>'Скасувати завантаження',
	'upload_file'=>'Завантажити файл',
	'loading'=>'Завантаження...',
	'rename'=>'Перейменувати',
	'show'=>'Показати',
	'hide'=>'Приховати',
	'showprevs'=>'Відображати прев\'юшки',
	'doprevs'=>'Створювати прев\'юшки',
	'watermark'=>'Watermark',
	'create_file'=>'Створити файл',
	'save'=>'Зберегти',
	'cancel'=>'Відмінити',
	'edit'=>'Редагувати',
	'update'=>'Оновити',
	'delete'=>'Видалити',
);