<?php
return array(
	#For Classes/Uploader.php
	'add_folder'=>'Create a folder',
	'open_folder'=>'Open folder',
	'insert_file'=>'Insert into editor (+ALT - dialogue)',
	'insert_attach'=>'Insert as object (+ALT - dialogue)',
	'open_file'=>'Open file',
	'go_up'=>'Up one level',
	'cancel_upload'=>'Cancel upload',
	'upload_file'=>'Upload file',
	'loading'=>'Loading...',
	'rename'=>'Rename',
	'show'=>'Show',
	'hide'=>'Hide',
	'showprevs'=>'Display thumbnails',
	'doprevs'=>'Create thumbnails',
	'watermark'=>'Watermark',
	'create_file'=>'Create file',
	'save'=>'Save',
	'cancel'=>'Cancel',
	'edit'=>'Edit',
	'update'=>'Update',
	'delete'=>'Delete',
);