<?php
return array(
	#For user/index.php
	'n'=>'News',
	'my'=>'My news',
	'deleted'=>'Successfully removed',
	'delc'=>'Confirm delete',
	'submit_del'=>'Do you really want to delete news &quot;%s&quot;?',
	'search_limit'=>'You can use the search again in %s seconds! Wait %s seconds.',
	'sym_limit'=>'The search query must be at least %s characters!',
	'notofind'=>'Not specified search criteria',
	'categs'=>'Categories',

	#For user/addedit.php
	'adding'=>'Adding news',
	'editing'=>'Aditing news',
	'FLOOD_LIMIT'=>'You can add news again in %s seconds! Wait %s seconds.',
	'ERROR_END_DATE'=>'Field &quot;Available until&quot; is filled incorrectly',
	'ERROR_END_DATE_IN_PAST'=>'Date &quot;Available until&quot; must be in future',
	'EMPTY_TITLE'=>function($l){return'Title can not be empty'.($l ? ' (for '.$l.')' : '');},
	'EMPTY_TEXT'=>function($l){return'Text can not be empty'.($l ? ' (for '.$l.')' : '');},
	'waitmod'=>'Waiting for moderation',
	'nssadded'=>'News successfully added',
	'nssedit'=>'News edited successfully',
	'FILL_AUTHOR'=>'Please introduce',

	#For template
	'all'=>'All news',
	'add'=>'Add news',
	'search'=>'Search',
	'tags_'=>'Tags: %s',
	'comments_'=>function($n,$l){return$l.($n==1 ? ' comment'  : ' comments');},
	'published_'=>'Published: %s',
	'category_'=>'Category: %s',
	'publisher_'=>'Published by: %s',
	'reads_'=>'Views: %s',
	'readmore'=>'Read more',
	'tags_list'=>'Tag list news',
	'newswt'=>'News with tag &quot;%s&quot;',
	'newsnotag'=>'Sorry, no news with tag &quot;%s&quot;.',
	'lookfor'=>'News search',
	'from'=>'News from category &quot;%s&quot;',
	'find'=>'Find',
	'or'=>'AND',
	'and'=>'OR',
	'for'=>'News for %s',
	'activated'=>'Activated',
	'deactivated'=>'Deactivated',
	'notfound'=>'Upon request, nothing found',
	'swhere'=>'Where to look',
	'titletext'=>'Title and text',
	'ta'=>'Title and announcement',
	'tat'=>'Title, announcement and text',
	'sortby'=>'Sort results by',
	'sdate'=>'Date',
	'srel'=>'Relevance',
	'modadd'=>'News &quot;%s&quot; successfully added. After being moderated, it might become available.',
	'modedit'=>'News &quot;%s&quot; successfully edited. After being moderated, it might become available.',
	'nomodadd'=>'News &quot;%s&quot; successfully added.',
	'nomodedit'=>'News &quot;%s&quot; successfully edited.',
	'statusadd'=>'You have successfully added news &quot;%s&quot;, but did not activate it for viewing by other users.',
	'statusedit'=>'You have successfully edited the news &quot;%s&quot;, but did not activate it for viewing by other users.',
	'goto'=>'Go to: %s',
	'pagewg'=>'page, where you came from',
	'deleting'=>'You have successfully removed news &quot;%s&quot;',

	#For form adding/editing material
	'nodraft'=>'Without draft',
	'title'=>'Title',
	'maincat'=>'Main category',
	'tags'=>'Tags',
	'ftags_'=>'Enter a comma-separated',
	'announcement'=>'Анонс',
	'announcement_'=>'Announcement of news is as annotation to book - must convince reader to read it',
	'text'=>'News text',
	'show_sokr'=>'Display a brief overview?',
	'show_sokr_'=>'for detailed viewing',
	'show_detail'=>'Show the link &quot;read more&quot;?',
	'show_detail_'=>'in the absence of detailed',
	'set_for_langs'=>'Set for languages',
	'captcha'=>'Security code',
	'captcha_'=>'type the characters you see',
	'status'=>'Status',
	'active'=>'Activate',
	'blocked'=>'Deactivate',
	'general'=>'General',
	'voting'=>'Voting',
	'enddate'=>'Available until',
	'enddate_'=>'With the arrival of this date, the news is no longer displayed on the site',
	'author'=>'Your name',
	'WRONG_CAPTCHA'=>'Security code is entered with error.',
);