<?php
/*
	Copyright © Eleanor CMS
	URL: http://eleanor-cms.ru, http://eleanor-cms.com
	E-mail: support@eleanor-cms.ru
	Developing: Alexander Sunvas*
	Interface: Rumin Sergey
	=====
	*Pseudonym
*/
if(!defined('CMS'))die;

class Update_6 extends UpdateClass
{	public static function Run()
	{		Eleanor::$Db->Update(P.'blocks',array('file'=>'addons/blocks/block_archive.php'),'`file`=\'addons/blocks/block_calendar.php\' AND `id`=3');
		Eleanor::$Db->Update(P.'blocks',array('file'=>'addons/blocks/block_menu_single.php'),'`file`=\'addons/menus/block.php\' AND `id`=5');

		Eleanor::$Db->Update(P.'blocks_l',array('title'=>'Archive'),'`id`=3 AND `language`=\'english\' AND `title`=\'Calendar\'');
		Eleanor::$Db->Update(P.'blocks_l',array('title'=>'Архив'),'`id`=3 AND `language`=\'russian\' AND `title`=\'Календарь\'');
		Eleanor::$Db->Update(P.'blocks_l',array('title'=>'Архів'),'`id`=3 AND `language`=\'ukrainian\' AND `title`=\'Календар\'');

		Eleanor::$Db->Query('CREATE TEMPORARY TABLE IF NOT EXISTS `tmp_config` (
`id` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
`group` smallint(5) unsigned NOT NULL,
`type` varchar(15) NOT NULL,
`name` varchar(50) NOT NULL,
`protected` tinyint(3) unsigned NOT NULL,
`position` smallint(5) unsigned NOT NULL,
`multilang` tinyint(3) unsigned NOT NULL,
`eval_load` mediumtext NOT NULL,
`eval_save` mediumtext NOT NULL,
PRIMARY KEY (`id`),
UNIQUE KEY `name` (`name`,`group`),
KEY `group` (`group`,`position`)
) ENGINE=InnoDB DEFAULT CHARSET='.DB_CHARSET);

		Eleanor::$Db->Query('CREATE TEMPORARY TABLE `tmp_config_l` (
`id` smallint(5) unsigned NOT NULL,
`language` varchar(15) NOT NULL DEFAULT \'\',
`title` tinytext NOT NULL,
`descr` text NOT NULL,
`value` text NOT NULL,
`serialized` tinyint(4) NOT NULL,
`default` text NOT NULL,
`extra` text NOT NULL,
`startgroup` varchar(100) NOT NULL,
PRIMARY KEY (`id`,`language`),
FULLTEXT KEY `title` (`title`,`descr`)
) ENGINE=MyISAM DEFAULT CHARSET='.DB_CHARSET);

		Eleanor::$Db->Query('INSERT INTO `tmp_config_l` SELECT * FROM `'.P.'config_l`');
		Eleanor::$Db->Query('INSERT INTO `tmp_config` SELECT * FROM `'.P.'config`');

		Eleanor::$Db->Query('ALTER TABLE `'.P.'config` CHANGE `position` `pos` SMALLINT UNSIGNED NOT NULL');
		Eleanor::$Db->Query('DELETE FROM `'.P.'config_groups` WHERE `id`=6');
		Eleanor::$Db->Query('DELETE FROM `'.P.'config_groups_l` WHERE `id`=6');
		Eleanor::$Db->Query('DELETE FROM `'.P.'config` WHERE `id`<=112');

		Eleanor::$Db->Query('INSERT INTO `'.P.<<<'SQL'
config` (`id`, `group`, `type`, `name`, `protected`, `pos`, `multilang`, `eval_load`, `eval_save`) VALUES
(1, 1, 'edit', 'site_domain', 1, 1, 0, '', 'if($co[''multilang''])\r\n{\r\n	foreach($co[''value''] as &$v)\r\n		$v=preg_replace(''#^(?:[a-z]{2,}://)?([a-z0-9\\-\\.]+).*$#i'',''\\1'',$v);\r\n	return$co[''value''];\r\n}\r\nelse\r\n	return preg_replace(''#^(?:[a-z]{2,}://)?([a-z0-9\\-\\.]+).*$#i'',''\\1'',$co[''value'']);'),
(2, 1, 'select', 'parked_domains', 1, 2, 0, '', ''),
(3, 1, 'edit', 'page_caching', 1, 3, 0, 'if($co[''multilang''])\r\n{\r\n	foreach($co[''value''] as &$v)\r\n		$v=abs(round((int)$v/60));\r\n}\r\nelse\r\n	$co[''value'']=abs(round((int)$co[''value'']/60));\r\nreturn$co;', 'if($co[''multilang''])\r\n{\r\n	foreach($co[''value''] as &$v)\r\n		$v=abs((int)$v)*60;\r\n	return$co[''value''];\r\n}\r\nreturn abs((int)$co[''value'']*60);'),
(4, 1, 'check', 'gzip', 1, 4, 0, '', ''),
(5, 1, 'edit', 'cookie_save_time', 1, 5, 0, 'if($co[''multilang''])\r\n	foreach($co[''value''] as &$v)\r\n		$v=round($v/86400);\r\nelse\r\n	$co[''value'']=round($co[''value'']/86400);\r\nreturn$co;', 'if($co[''multilang''])\r\n{\r\n	foreach($co[''value''] as &$v)\r\n		$v=abs((int)$v*86400);\r\n	return$co[''value''];\r\n}\r\nreturn abs((int)$co[''value'']*86400);'),
(6, 1, 'edit', 'cookie_domain', 1, 6, 0, '', ''),
(7, 1, 'edit', 'cookie_prefix', 1, 7, 0, '', ''),
(8, 1, 'items', 'guest_group', 1, 8, 0, '', ''),
(9, 1, 'check', 'bots_enable', 1, 9, 0, '', ''),
(10, 1, 'items', 'bot_group', 1, 10, 0, '', ''),
(11, 1, 'text', 'bots_list', 0, 11, 0, 'if($co[''multilang''])\r\n	foreach($co[''value''] as &$v)\r\n	{\r\n		foreach($v as $k=>&$bot)\r\n			$bot=$k.''=''.$bot;\r\n		$v=join("\n",$v);\r\n	}\r\nelse\r\n{\r\n	foreach($co[''value''] as $k=>&$bot)\r\n		$bot=$k.''=''.$bot;\r\n	$co[''value'']=join("\n",$co[''value'']);\r\n}\r\nreturn$co;', 'if($co[''multilang''])\r\n{\r\n	foreach($co[''value''] as &$v)\r\n	{\r\n		$res=array();\r\n		$v=str_replace("\r",'''',$v);\r\n		foreach(explode("\n",$v) as $bot)\r\n			if(strpos($bot,''='')!==false)\r\n			{\r\n				list($uagent,$name)=explode(''='',$bot,2);\r\n				$res[$uagent]=$name;\r\n			}\r\n		$v=$res;\r\n	}\r\n	return$co[''value''];\r\n}\r\nelse\r\n{\r\n	$v=str_replace("\r",'''',$co[''value'']);\r\n	$res=array();\r\n	foreach(explode("\n",$v) as $bot)\r\n		if(strpos($bot,''='')!==false)\r\n		{\r\n			list($uagent,$name)=explode(''='',$bot,2);\r\n			$res[$uagent]=$name;\r\n		}\r\n	return $res;\r\n}'),
(12, 1, 'check', 'multilang', 1, 12, 0, 'if(count(Eleanor::$langs)==1)\r\n	if($co[''multilang''])\r\n	{\r\n		$co[''options''][''extra''][''disabled'']=''disabled'';\r\n		foreach($co[''value''] as &$v)\r\n			$v=0;\r\n	}\r\n	else\r\n	{\r\n		$co[''value'']=0;\r\n		$co[''options''][''extra''][''disabled'']=''disabled'';\r\n	}\r\nreturn$co;', ''),
(13, 1, 'select', 'time_zone', 1, 13, 0, '', ''),
(14, 1, 'text', 'blocked_ips', 1, 14, 0, '', ''),
(15, 1, 'edit', 'blocked_message', 1, 15, 1, '', ''),
(16, 2, 'edit', 'site_name', 1, 1, 1, '', ''),
(17, 2, 'edit', 'site_defis', 1, 2, 1, '', ''),
(18, 2, 'text', 'site_description', 1, 3, 1, '', ''),
(19, 2, 'check', 'furl', 1, 4, 0, '', ''),
(20, 2, 'check', 'trans_uri', 1, 5, 0, '', ''),
(21, 2, 'edit', 'url_static_delimiter', 1, 6, 0, '', 'if($co[''multilang''])\r\n	foreach($co[''value''] as &$v)\r\n	{\r\n		$v=preg_replace(''/[a-z0-9''.constant(Language::$main.''::ALPHABET'').'']+/i'','''',$v);\r\n		if(!$v)\r\n			$v=''/'';\r\n	}\r\nelse\r\n{\r\n	$co[''value'']=preg_replace(''/[a-z0-9''.constant(Language::$main.''::ALPHABET'').'']+/i'','''',$co[''value'']);\r\n	if(!$co[''value''])\r\n		$co[''value'']=''/'';\r\n}\r\n	return$co[''value''];'),
(22, 2, 'edit', 'url_static_defis', 1, 7, 0, '', 'if($co[''multilang''])\r\n	foreach($co[''value''] as &$v)\r\n	{\r\n		$v=preg_replace(''/[a-z0-9''.constant(Language::$main.''::ALPHABET'').'']+/i'','''',$v);\r\n		if(!$v)\r\n			$v=''_'';\r\n	}\r\nelse\r\n{\r\n	$co[''value'']=preg_replace(''/[a-z0-9''.constant(Language::$main.''::ALPHABET'').'']+/i'','''',$co[''value'']);\r\n	if(!$co[''value''])\r\n		$co[''value'']=''_'';\r\n}\r\nreturn$co[''value''];'),
(23, 2, 'edit', 'url_static_ending', 1, 8, 0, '', 'if($co[''multilang''])\r\n{\r\n	foreach($co[''value''] as &$v)\r\n		if(preg_match(''/^[^a-z0-9''.constant(Language::$main.''::ALPHABET'').'']/i'',$v)==0)\r\n			$v=''.''.$v;\r\n}\r\nelse\r\n{\r\n	if(preg_match(''/^[^a-z0-9''.constant(Language::$main.''::ALPHABET'').'']/i'',$co[''value''])==0)\r\n		$co[''value'']=''.''.$co[''value''];\r\n}\r\nreturn$co[''value''];'),
(24, 2, 'edit', 'url_rep_space', 1, 9, 0, '', 'if($co[''multilang''])\r\n	foreach($co[''value''] as &$v)\r\n	{\r\n		$v=preg_replace(''/[a-z0-9''.constant(Language::$main.''::ALPHABET'').'']+/i'','''',$v);\r\n		if(!$v)\r\n			$v=''-'';\r\n	}\r\nelse\r\n{\r\n	$co[''value'']=preg_replace(''/[a-z0-9''.constant(Language::$main.''::ALPHABET'').'']+/i'','''',$co[''value'']);\r\n	if(!$co[''value''])\r\n		$co[''value'']=''-'';\r\n}\r\nreturn$co[''value''];'),
(25, 2, 'select', 'prefix_free_module', 1, 10, 0, '', ''),
(26, 2, 'check', 'site_closed', 1, 11, 0, '', ''),
(27, 2, 'editor', 'site_close_mes', 1, 12, 1, '', ''),
(28, 2, 'select', 'show_status', 1, 13, 0, '', ''),
(29, 2, 'items', 'templates', 1, 14, 0, '', ''),
(30, 3, 'edit', 'link_options', 1, 1, 1, '', ''),
(31, 3, 'edit', 'link_register', 1, 2, 1, '', ''),
(32, 3, 'edit', 'link_passlost', 1, 3, 1, '', ''),
(33, 3, 'user', 'time_online', 1, 4, 0, '', ''),
(34, 3, 'select', 'antibrute', 1, 5, 0, '', ''),
(35, 3, 'edit', 'antibrute_cnt', 1, 6, 0, '', 'if($co[''multilang''])\r\n{\r\n	foreach($co[''value''] as &$v)\r\n		$v=abs((int)$v);\r\n	return$co[''value''];\r\n}\r\nreturn abs((int)$co[''value'']);'),
(36, 3, 'edit', 'antibrute_time', 1, 7, 0, 'if($co[''multilang''])\r\n	foreach($co[''value''] as &$v)\r\n		$v=round($v/60);\r\nelse\r\n	$co[''value'']=round($co[''value'']/60);\r\nreturn$co;', 'if($co[''multilang''])\r\n{\r\n	foreach($co[''value''] as &$v)\r\n		$v=abs((int)$v*60);\r\n	return$co[''value''];\r\n}\r\nreturn abs((int)$co[''value'']*60);'),
(37, 4, 'text', 'blocked_names', 1, 1, 0, '', ''),
(38, 4, 'text', 'blocked_emails', 1, 2, 0, '', ''),
(39, 4, 'select', 'reg_type', 1, 3, 0, '', ''),
(40, 4, 'input', 'reg_act_time', 1, 4, 0, 'if($co[''multilang''])\r\n{\r\n	foreach($co[''value''] as &$v)\r\n		$v=abs(round((int)$v/3600));\r\n}\r\nelse\r\n	$co[''value'']=abs(round((int)$co[''value'']/3600));\r\nreturn$co;', 'if($co[''multilang''])\r\n{\r\n	foreach($co[''value''] as &$v)\r\n		$v=abs((int)$v)*3600;\r\n	return$co[''value''];\r\n}\r\nreturn abs((int)$co[''value'']*3600);'),
(41, 4, 'select', 'reg_unactivated', 1, 5, 0, '', ''),
(42, 4, 'check', 'reg_off', 1, 6, 0, '', ''),
(43, 4, 'edit', 'max_name_length', 1, 7, 0, '', 'if($co[''multilang''])\r\n	foreach($co[''value''] as &$v)\r\n	{\r\n		$v=abs((int)$v);\r\n		if($v<5)\r\n			$v=5;\r\n	}\r\nelse\r\n{\r\n	$co[''value'']=abs((int)$co[''value'']);\r\n	if($co[''value'']<5)\r\n		$co[''value'']=5;\r\n}\r\nreturn$co[''value''];'),
(44, 4, 'edit', 'min_pass_length', 1, 8, 0, '', 'if($co[''multilang''])\r\n{\r\n	foreach($co[''value''] as &$v)\r\n		$v=abs((int)$v);\r\n	return$co[''value''];\r\n}\r\nreturn abs((int)$co[''value'']);'),
(45, 4, 'edit', 'avatar_bytes', 1, 9, 0, 'if($co[''multilang''])\r\n{\r\n	foreach($co[''value''] as &$v)\r\n		$v=abs(round((int)$v/1024));\r\n}\r\nelse\r\n	$co[''value'']=abs(round((int)$co[''value'']/1024));\r\nreturn$co;', 'if($co[''multilang''])\r\n{\r\n	foreach($co[''value''] as &$v)\r\n		$v=abs((int)$v)*1024;\r\n	return$co[''value''];\r\n}\r\nreturn abs((int)$co[''value'']*1024);'),
(46, 4, 'edit', 'avatar_size', 1, 10, 0, '', 'if($co[''multilang''])\r\n{\r\n	foreach($co[''value''] as &$v)\r\n		if(preg_match(''#^\\d+ \\d+$#'',$v)==0)\r\n			throw new EE(''incorrect_format'',EE::USER,array(''lang''=>true));\r\n}\r\nelseif(preg_match(''#^\\d+ \\d+$#'',$co[''value''])==0)\r\n	throw new EE(''incorrect_format'',EE::USER,array(''lang''=>true));\r\nreturn$co[''value''];'),
(47, 4, 'select', 'account_pass_rec_t', 1, 11, 0, '', ''),
(48, 5, 'edit', 'captcha_length', 1, 1, 0, '', 'if($co[''multilang''])\r\n{\r\n	foreach($co[''value''] as &$v)\r\n		$v=abs((int)$v);\r\n	return$co[''value''];\r\n}\r\nreturn abs((int)$co[''value'']);'),
(49, 5, 'edit', 'captcha_symbols', 1, 2, 0, '', ''),
(50, 5, 'edit', 'captcha_width', 1, 3, 0, '', 'if($co[''multilang''])\r\n{\r\n	foreach($co[''value''] as &$v)\r\n		$v=abs((int)$v);\r\n	return$co[''value''];\r\n}\r\nreturn abs((int)$co[''value'']);'),
(51, 5, 'edit', 'captcha_height', 1, 4, 0, '', 'if($co[''multilang''])\r\n{\r\n	foreach($co[''value''] as &$v)\r\n		$v=abs((int)$v);\r\n	return$co[''value''];\r\n}\r\nreturn abs((int)$co[''value'']);'),
(52, 5, 'edit', 'captcha_fluctuation', 1, 5, 0, '', 'if($co[''multilang''])\r\n{\r\n	foreach($co[''value''] as &$v)\r\n		$v=abs((int)$v);\r\n	return$co[''value''];\r\n}\r\nreturn abs((int)$co[''value'']);'),
(53, 7, 'select', 'mail_method', 1, 1, 0, '', ''),
(54, 7, 'edit', 'mail_from', 1, 2, 0, '', 'if(!Strings::CheckEmail($co[''value'']))\r\n	throw new EE(''incorrect_email'',EE::USER,array(''lang''=>true));\r\nreturn$co[''value''];'),
(55, 7, 'select', 'mail_priority', 1, 3, 0, '', ''),
(56, 7, 'edit', 'mail_reply', 1, 4, 0, '', 'if(!Strings::CheckEmail($co[''value''],false))\r\n	throw new EE(''incorrect_email'',EE::USER,array(''lang''=>true));\r\nreturn$co[''value''];'),
(57, 7, 'edit', 'mail_notice', 1, 5, 0, '', 'if(!Strings::CheckEmail($co[''value''],false))\r\n	throw new EE(''incorrect_email'',EE::USER,array(''lang''=>true));\r\nreturn$co[''value''];'),
(58, 7, 'edit', 'mail_smtp_user', 1, 6, 0, '', ''),
(59, 7, 'edit', 'mail_smtp_pass', 1, 7, 0, '', ''),
(60, 7, 'edit', 'mail_smtp_host', 1, 8, 0, '', ''),
(61, 7, 'edit', 'mail_smtp_port', 1, 9, 0, '', ''),
(62, 8, 'select', 'editor_type', 1, 1, 0, '', ''),
(63, 8, 'text', 'bad_words', 1, 2, 0, '', ''),
(64, 8, 'edit', 'bad_words_replace', 1, 3, 1, '', ''),
(65, 8, 'select', 'antidirectlink', 1, 4, 0, '', ''),
(66, 8, 'check', 'autoparse_urls', 1, 5, 0, '', ''),
(67, 9, 'uploadimage', 'rss_image', 1, 1, 0, '', ''),
(68, 10, 'select', 'comments_sort', 1, 1, 0, '', ''),
(69, 10, 'edit', 'comments_pp', 1, 2, 0, '', 'if($co[''multilang''])\r\n	foreach($co[''value''] as &$v)\r\n	{\r\n		$v=abs((int)$v);\r\n		if($v==0)\r\n			$v=10;\r\n	}\r\nelse\r\n{\r\n	$co[''value'']=abs((int)$co[''value'']);\r\n	if($co[''value'']==0)\r\n		$co[''value'']=10;\r\n}\r\nreturn$co[''value''];'),
(70, 10, 'edit', 'comments_timelimit', 1, 3, 0, '', 'if($co[''multilang''])\r\n{\r\n	foreach($co[''value''] as &$v)\r\n		$v=abs((int)$v);\r\n	return$co[''value''];\r\n}\r\nreturn abs((int)$co[''value'']);'),
(71, 10, 'items', 'comments_display_for', 1, 5, 0, '', ''),
(72, 10, 'items', 'comments_post_for', 1, 6, 0, '', ''),
(73, 11, 'check', 'thumbs', 1, 1, 0, '', ''),
(74, 11, 'edit', 'thumb_types', 1, 2, 0, '', ''),
(75, 11, 'edit', 'thumb_width', 1, 3, 0, '', 'if($co[''multilang''])\r\n{\r\n	foreach($co[''value''] as &$v)\r\n		$v=abs((int)$v);\r\n}\r\nelse\r\n	$co[''value'']=abs((int)$co[''value'']);\r\nreturn$co[''value''];'),
(76, 11, 'edit', 'thumb_height', 1, 4, 0, '', 'if($co[''multilang''])\r\n{\r\n	foreach($co[''value''] as &$v)\r\n		$v=abs((int)$v);\r\n}\r\nelse\r\n	$co[''value'']=abs((int)$co[''value'']);\r\nreturn$co[''value''];'),
(77, 11, 'select', 'thumb_reducing', 1, 5, 0, '', ''),
(78, 11, 'select', 'thumb_first', 1, 6, 0, '', ''),
(79, 11, 'check', 'watermark', 1, 7, 0, '', ''),
(80, 11, 'edit', 'watermark_types', 1, 8, 0, '', ''),
(81, 11, 'edit', 'watermark_alpha', 1, 9, 0, '', 'if($co[''multilang''])\r\n{\r\n	foreach($co[''value''] as &$v)\r\n	{\r\n		$v=abs((int)$v);\r\n		if($v>100)\r\n			$v=100;\r\n	}\r\n}\r\nelse\r\n{\r\n	$co[''value'']=abs((int)$co[''value'']);\r\n	if($co[''value'']>100)\r\n		$co[''value'']=100;\r\n}\r\nreturn$co[''value''];'),
(82, 11, 'edit', 'watermark_top', 1, 10, 0, '', 'if($co[''multilang''])\r\n{\r\n	foreach($co[''value''] as &$v)\r\n	{\r\n		$v=abs((int)$v);\r\n		if($v>100)\r\n			$v=100;\r\n	}\r\n}\r\nelse\r\n{\r\n	$co[''value'']=abs((int)$co[''value'']);\r\n	if($co[''value'']>100)\r\n		$co[''value'']=100;\r\n}\r\nreturn$co[''value''];'),
(83, 11, 'edit', 'watermark_left', 1, 11, 0, '', 'if($co[''multilang''])\r\n{\r\n	foreach($co[''value''] as &$v)\r\n	{\r\n		$v=abs((int)$v);\r\n		if($v>100)\r\n			$v=100;\r\n	}\r\n}\r\nelse\r\n{\r\n	$co[''value'']=abs((int)$co[''value'']);\r\n	if($co[''value'']>100)\r\n		$co[''value'']=100;\r\n}\r\nreturn$co[''value''];'),
(84, 11, 'edit', 'watermark_image', 1, 12, 0, '', ''),
(85, 11, 'edit', 'watermark_string', 1, 13, 1, '', ''),
(86, 11, 'edit', 'watermark_csa', 1, 14, 0, '', 'if($co[''multilang''])\r\n{\r\n	foreach($co[''value''] as &$v)\r\n		if(preg_match(''#^\\d+,\\d+,\\d+,\\d+,\\d+$#'',$v)==0)\r\n			throw new EE(''incorrect_format'',EE::USER,array(''lang''=>true));\r\n}\r\nelse\r\n{\r\n	if(preg_match(''#^\\d+,\\d+,\\d+,\\d+,\\d+$#'',$co[''value''])==0)\r\n		throw new EE(''incorrect_format'',EE::USER,array(''lang''=>true));\r\n}\r\nreturn$co[''value''];'),
(87, 11, 'check', 'download_antileech', 1, 15, 0, '', ''),
(88, 11, 'check', 'download_no_session', 1, 16, 0, '', ''),
(89, 12, 'edit', 'multisite_secret', 0, 1, 0, '', ''),
(90, 12, 'edit', 'multisite_ttl', 0, 2, 0, '', 'if($co[''multilang''])\r\n{\r\n	foreach($co[''value''] as &$v)\r\n		$v=abs((int)$v);\r\n	return$co[''value''];\r\n}\r\nreturn abs((int)$co[''value'']);'),
(91, 13, 'edit', 'drafts_days', 0, 1, 0, '', 'if($co[''multilang''])\r\n{\r\n	foreach($co[''value''] as &$v)\r\n		$v=(int)$v;\r\n	return$co[''value''];\r\n}\r\nreturn(int)$co[''value''];'),
(92, 13, 'edit', 'drafts_autosave', 0, 2, 0, '', 'if($co[''multilang''])\r\n{\r\n	foreach($co[''value''] as &$v)\r\n		$v=(int)$v;\r\n	return$co[''value''];\r\n}\r\nreturn(int)$co[''value''];'),
(93, 14, 'user', 'm_static_general', 1, 1, 0, '', ''),
(94, 15, 'edit', 'publ_per_page', 0, 1, 0, '', 'if($co[''multilang''])\r\n{\r\n	foreach($co[''value''] as &$v)\r\n		$v=abs((int)$v);\r\n	return$co[''value''];\r\n}\r\nreturn abs((int)$co[''value'']);'),
(95, 15, 'edit', 'publ_rss_per_page', 0, 3, 0, '', 'if($co[''multilang''])\r\n{\r\n	foreach($co[''value''] as &$v)\r\n		$v=abs((int)$v);\r\n	return$co[''value''];\r\n}\r\nreturn abs((int)$co[''value'']);'),
(96, 15, 'check', 'publ_add', 0, 4, 0, '', ''),
(97, 15, 'check', 'publ_catsubcat', 0, 5, 0, '', ''),
(98, 15, 'check', 'publ_ping', 0, 6, 0, '', ''),
(99, 15, 'check', 'publ_rating', 0, 7, 0, '', ''),
(100, 15, 'check', 'publ_mark_details', 0, 8, 0, '', ''),
(101, 15, 'check', 'publ_mark_users', 0, 9, 0, '', ''),
(102, 15, 'edit', 'publ_remark', 0, 10, 0, '', 'if($co[''multilang''])\r\n	foreach($co[''value''] as &$v)\r\n		$v=max((int)$v,1);\r\nelse\r\n	$co[''value'']=max((int)$co[''value''],1);\r\nreturn$co[''value''];'),
(103, 15, 'edit', 'publ_lowmark', 0, 11, 0, '', 'if($co[''multilang''])\r\n	foreach($co[''value''] as &$v)\r\n		$v=min((int)$v,0);\r\nelse\r\n	$co[''value'']=min((int)$co[''value''],0);\r\nreturn$co[''value''];'),
(104, 15, 'edit', 'publ_highmark', 0, 12, 0, '', 'if($co[''multilang''])\r\n	foreach($co[''value''] as &$v)\r\n		$v=max((int)$v,0);\r\nelse\r\n	$co[''value'']=max((int)$co[''value''],0);\r\nreturn$co[''value''];')
SQL
);

		Eleanor::$Db->Delete(P.'config_l','`id`<=112');
		Eleanor::$Db->Query('INSERT INTO `'.P.<<<'SQL'
config_l` (`id`, `language`, `title`, `descr`, `value`, `serialized`, `default`, `extra`, `startgroup`) VALUES
(1, 'russian', 'Основной домен', 'Вводится без приставки http://', 'eleanor.ru', 0, 'eleanor.ru', '', 'Домен'),
(2, 'russian', 'Поддержка паркованных доменов', 'При запуске сайта на паркованном домене', 'redirect', 0, 'redirect', 'array(\r\n		''options''=>array(\r\n			''ignore''=>''Игнорировать'',\r\n			''redirect''=>''Перенаправить все ссылки на основной домен'',\r\n			''rel''=>''Добавить rel canonical'',\r\n		),\r\n	)', ''),
(3, 'russian', 'Кеширование страниц браузером', 'Введите стандартный срок кеширования страницы в минутах. 0 - отключить кеширование.', '600', 0, '600', '', 'Оптимизация нагрузки'),
(4, 'russian', 'Включать GZIP сжатие?', 'Включение этой опции позволит сэкономить трафик', '1', 0, '1', '', ''),
(5, 'russian', 'Срок хранения cookie (в днях)', '', '31536000', 0, '31536000', '', 'Cookies'),
(6, 'russian', 'Домен cookie', 'Используйте .example.com для глобальных cookie. Обратите внимание на точку перед именем домена. Вместо "example.com" используейте ваше доменное имя. Если включена поддержка паркованных домено, вместо имени домена используйте *.', '.*', 0, '.*', '', ''),
(7, 'russian', 'Префикс сookie', 'Данная опция позволяет избежать конфликтов, если на домене кроме системы расположены и другие скрипты, использующие cookies', 'el', 0, 'el', '', ''),
(8, 'russian', 'Группа гостей', 'Наделить гостей правами группы...', 'a:1:{i:0;s:1:"3";}', 1, 'a:1:{i:0;s:1:"3";}', 'include Eleanor::$root.''addons/admin/options/groups.php'';', 'Права по умолчанию'),
(9, 'russian', 'Отслеживать поисковых ботов?', '', '1', 0, '1', '', ''),
(10, 'russian', 'Группа поисковых ботов', 'Наделить поисковых ботов правами группы...', 'a:1:{i:0;s:1:"4";}', 1, 'a:1:{i:0;s:1:"4";}', 'include Eleanor::$root.''addons/admin/options/groups.php'';', ''),
(11, 'russian', 'Список поисковых ботов', 'Здесь хранятся данные о поисковых ботах. Формат ввода: по одному с каждой строки в виде <b>user agent=имя бота</b>.', 'a:32:{s:9:"googlebot";s:10:"Google Bot";s:13:"slurp@inktomi";s:7:"Hot Bot";s:11:"archive_org";s:15:"Archive.org Bot";s:10:"Ask Jeeves";s:14:"Ask Jeeves Bot";s:5:"Lycos";s:9:"Lycos Bot";s:9:"WhatUSeek";s:17:"What You Seek Bot";s:11:"ia_archiver";s:15:"IA.Archiver Bot";s:9:"GigaBlast";s:13:"Gigablast Bot";s:7:"Gigabot";s:13:"Gigablast Bot";s:6:"Yandex";s:10:"Yandex Bot";s:6:"Yahoo!";s:9:"Yahoo Bot";s:15:"Yahoo-MMCrawler";s:20:"Yahoo-MM Crawler Bot";s:13:"TurtleScanner";s:18:"Turtle Scanner Bot";s:11:"TurnitinBot";s:12:"Turnitin Bot";s:8:"ZipppBot";s:9:"Zippp Bot";s:12:"StackRambler";s:17:"Stack Rambler Bot";s:4:"oBot";s:4:"oBot";s:7:"rambler";s:11:"Rambler Bot";s:6:"Jetbot";s:7:"Jet Bot";s:8:"NaverBot";s:9:"Naver Bot";s:6:"libwww";s:9:"Punto Bot";s:5:"aport";s:9:"Aport Bot";s:6:"msnbot";s:7:"MSN Bot";s:11:"MnoGoSearch";s:17:"Mno Go Search Bot";s:5:"booch";s:9:"Booch Bot";s:7:"Openbot";s:12:"Openfind Bot";s:7:"scooter";s:13:"Altavista Bot";s:10:"WebCrawler";s:8:"Fast Bot";s:6:"WebZIP";s:10:"WebZIP Bot";s:8:"GetSmart";s:13:"Get Smart Bot";s:11:"grub-client";s:15:"Grub Client Bot";s:7:"Vampire";s:15:"Net Vampire Bot";}', 1, 'a:32:{s:9:"googlebot";s:10:"Google Bot";s:13:"slurp@inktomi";s:7:"Hot Bot";s:11:"archive_org";s:15:"Archive.org Bot";s:10:"Ask Jeeves";s:14:"Ask Jeeves Bot";s:5:"Lycos";s:9:"Lycos Bot";s:9:"WhatUSeek";s:17:"What You Seek Bot";s:11:"ia_archiver";s:15:"IA.Archiver Bot";s:9:"GigaBlast";s:13:"Gigablast Bot";s:7:"Gigabot";s:13:"Gigablast Bot";s:6:"Yandex";s:10:"Yandex Bot";s:6:"Yahoo!";s:9:"Yahoo Bot";s:15:"Yahoo-MMCrawler";s:20:"Yahoo-MM Crawler Bot";s:13:"TurtleScanner";s:18:"Turtle Scanner Bot";s:11:"TurnitinBot";s:12:"Turnitin Bot";s:8:"ZipppBot";s:9:"Zippp Bot";s:12:"StackRambler";s:17:"Stack Rambler Bot";s:4:"oBot";s:4:"oBot";s:7:"rambler";s:11:"Rambler Bot";s:6:"Jetbot";s:7:"Jet Bot";s:8:"NaverBot";s:9:"Naver Bot";s:6:"libwww";s:9:"Punto Bot";s:5:"aport";s:9:"Aport Bot";s:6:"msnbot";s:7:"MSN Bot";s:11:"MnoGoSearch";s:17:"Mno Go Search Bot";s:5:"booch";s:9:"Booch Bot";s:7:"Openbot";s:12:"Openfind Bot";s:7:"scooter";s:13:"Altavista Bot";s:10:"WebCrawler";s:8:"Fast Bot";s:6:"WebZIP";s:10:"WebZIP Bot";s:8:"GetSmart";s:13:"Get Smart Bot";s:11:"grub-client";s:15:"Grub Client Bot";s:7:"Vampire";s:15:"Net Vampire Bot";}', '', ''),
(12, 'russian', 'Включить многоязыковую поддержку?', '', '1', 0, '1', '', 'Локализация'),
(13, 'russian', 'Часовой пояс по-умолчанию', '', 'Europe/Kiev', 0, 'Europe/Kiev', 'include Eleanor::$root.''addons/admin/options/tz.php''', ''),
(14, 'russian', 'Заблокированные IP адреса', 'Каждый адрес — с новой строки. Допускаются маски вида 87.183.*.*, а так же диапазоны вида 79.224.60.1-79.224.60.255 с поддержкой масок. Чтобы указать уникальную причину бана после введённого IP адреса, поставьте = и напишите причину. Например: 87.183.*.*=Отбросам здесь не место!', '', 0, '', 'array(''extra''=>array(''style''=>''word-wrap:normal''));', 'Бан по IP'),
(15, 'russian', 'Сообщение для заблокированных', 'Это сообщение увидят пользователи, для которых не введена причина.', ':-p', 0, ':-p', '', ''),
(16, 'russian', 'Название сайта', '', '', 0, '', '', 'Заголовки сайта'),
(17, 'russian', 'Разделитель заголовков', '', ' - ', 0, ' - ', '', ''),
(18, 'russian', 'Описание сайта', '', 'Сайт построен на системе управления сайтом Eleanor', 0, 'Сайт построен на системе управления сайтом Eleanor', '', ''),
(19, 'russian', 'Включить статические ссылки?', '', '1', 0, '1', '', 'Настройка ссылок'),
(20, 'russian', 'Транслитерировать статические ссылки?', 'Статические ссылки контента, а также имена загружаемых файлов будут автоматически транслитерированы.', '0', 0, '0', '', ''),
(21, 'russian', 'Разделитель параметров', 'В ссылке <q>news<b>/</b>category<b>/</b>news<b>/</b>page_1.html</q> разделителем параметров является косая черта / (слеш).\r\nДля ввода допускаются любые не буквенные символы.', '/', 0, '/', '', ''),
(22, 'russian', 'Разделитель значений', 'В ссылке <q>news/category/news/page<b>_</b>1.html</q> разделителем значений является нижний прочерк _.\r\nДля ввода допускаются любые не буквенные символы.', '_', 0, '_', '', ''),
(23, 'russian', 'Окончание статических ссылок', 'В ссылке <q>news/category/news/page_1<b>.html</b></q> окончанием является <q>.html</q>.\r\nОбратите внимание, что начинаться это поле должно с не буквенного символа!', '.html', 0, '.html', '', ''),
(24, 'russian', 'Автозамена недопустимых символов в статичных ссылках', 'Значение не должно совпадать ни с разделителем параметров, ни с разделителем значений, ни с окончанием статических ссылок и так же должно начинаться с не буквенного символа.', '-', 0, '-', '', ''),
(25, 'russian', 'Модуль без префикса', 'Ссылки этого модуля будут работать без указания префикса-идентификатора модуля', '2', 0, '2', 'include Eleanor::$root.''addons/admin/options/lfm.php''', ''),
(26, 'russian', 'Выключить сайт?', 'Сайт будет доступен только группам, для которых включена опция просмотра закрытого сайта', '0', 0, '0', '', 'Выключение сайта'),
(27, 'russian', 'Причина выключения сайта', '', '', 0, '', 'array(''type''=>-1)', ''),
(28, 'russian', 'Информация о генерации страницы', 'Информация внизу страницы, содержащая скорость генерации страницы, количество использованных запросов в базу данных, статус GZIP сжатия и количество затраченной памяти.', '2', 0, '2', 'array(\r\n		''options''=>array(''Скрыть'',''Отображать только администраторам'',''Отображать всем''),\r\n	)', 'Дополнительная информация'),
(29, 'russian', 'Шаблоны на выбор', 'Укажите шаблоны, которые пользователи смогут выбирать в качестве оформления сайта.', 'a:1:{i:0;s:5:"Uniel";}', 1, 'a:1:{i:0;s:5:"Uniel";}', 'include Eleanor::$root.''addons/admin/options/templates.php''', 'Разное'),
(30, 'russian', 'Ссылка личного кабинета', 'Обратите внимание, что запись <q>param1=value1<b>&amp;</b>param2=value2</q> некорректна. Корректная запись: <q>param1=value1<b>&amp;amp;</b>param2=value2</q>', '%D0%B0%D0%BA%D0%BA%D0%B0%D1%83%D0%BD%D1%82.html', 0, '%D0%B0%D0%BA%D0%BA%D0%B0%D1%83%D0%BD%D1%82.html', '', 'Ссылки'),
(31, 'russian', 'Ссылка на регистрацию', 'Обратите внимание, что запись <q>param1=value1<b>&amp;</b>param2=value2</q> некорректна. Корректная запись: <q>param1=value1<b>&amp;amp;</b>param2=value2</q>', '%D0%B0%D0%BA%D0%BA%D0%B0%D1%83%D0%BD%D1%82/register', 0, '%D0%B0%D0%BA%D0%BA%D0%B0%D1%83%D0%BD%D1%82/register', '', ''),
(32, 'russian', 'Ссылка на восстановление пароля', 'Обратите внимание, что запись <q>param1=value1<b>&amp;</b>param2=value2</q> некорректна. Корректная запись: <q>param1=value1<b>&amp;amp;</b>param2=value2</q>', '%D0%B0%D0%BA%D0%BA%D0%B0%D1%83%D0%BD%D1%82/lostpass', 0, '%D0%B0%D0%BA%D0%BA%D0%B0%D1%83%D0%BD%D1%82/lostpass', '', ''),
(33, 'russian', 'Длительность сессий', 'Количество секунд во время которых пользователь считается онлайн после проявления активности.', 'a:4:{s:10:"LoginAdmin";i:900;s:9:"LoginBase";i:900;s:10:"LoginModer";i:300;s:7:"LoginNo";i:10;}', 1, 'a:4:{s:10:"LoginAdmin";i:900;s:9:"LoginBase";i:900;s:10:"LoginModer";i:300;s:7:"LoginNo";i:10;}', 'include Eleanor::$root.''addons/admin/options/time_online.php''', 'Параметры аутентификации и авторизации'),
(34, 'russian', 'Тип защиты', '', '1', 0, '1', 'array(\r\n		''options''=>array(''Отключена'',''Лимит попыток за определенное время'',''Отображать капчу после исчерпания лимита попыток входа''),\r\n	)', 'Защита от подбора пароля'),
(35, 'russian', 'Максимальное число неудачных попыток аутентификации', '', '5', 0, '5', '', ''),
(36, 'russian', 'Максимальный промежуток времени в минутах, во время которого допускаются неудачные попытки аутентификации', 'Пример: если максимальное число неудачных попыток аутентификации равно 5, а заданное значение равно 15, то пользователь будет заблокирован в случае если за последние 15 минут было 5 неудачных попыток входа.', '600', 0, '600', '', ''),
(37, 'russian', 'Заблокированные ники', 'Через запятую. Допустимые спецсимволы: * - любая последовательность символов, ? - любой один символ.', '', 0, '', '', 'Блокировки'),
(38, 'russian', 'Заблокированные e-mail', 'Через запятую. Допустимые спецсимволы: * - любая последовательность символов, ? - любой один символ.', '', 0, '', '', ''),
(39, 'russian', 'Активация новосозданного пользователя', '', '1', 0, '1', 'array(\r\n		''options''=>array(1=>''Не требуется'',''Через e-mail'',''Вручную администратором''),\r\n	)', 'Регистрация'),
(40, 'russian', 'Срок активации', 'Количество часов отведенных для активации учетной записи', '86400', 0, '86400', 'array(''type''=>''number'',''extra''=>array(''min''=>1));', ''),
(41, 'russian', 'Как поступать с неактивированными учетными записями', '', '1', 0, '1', 'array(\r\n		''options''=>array(1=>''Удалить'',''Ничего не делать''),\r\n	)', ''),
(42, 'russian', 'Отключить регистрацию?', '', '0', 0, '0', '', ''),
(43, 'russian', 'Максимальная длина ника', '', '15', 0, '15', '', ''),
(44, 'russian', 'Минимальная длина пароля', '', '7', 0, '7', '', ''),
(45, 'russian', 'Максимальный размер загружаемого аватара в KB', '', '307200', 0, '307200', '', 'Профиль'),
(46, 'russian', 'Максимальный размер аватара', 'Вводить нужно в формате: ширина[пробел]высота.', '100 100', 0, '100 100', '', ''),
(47, 'russian', 'Восстановление пароля', '', '1', 0, '1', 'array(\r\n		''options''=>array(''Запрещено'',''Позволить ввести новый пароль'',''Сгенерировать и выслать пароль на e-mail''),\r\n	);', ''),
(48, 'russian', 'Количество символов в captcha', '', '5', 0, '5', '', 'Настройки captcha'),
(49, 'russian', 'Алфавит captcha', 'Символы, используемые в captcha (желательно исключить похожие символы, как 0— цифра и o — буква)', '23456789abcdeghkmnpqsuvxyz', 0, '23456789abcdeghkmnpqsuvxyz', '', ''),
(50, 'russian', 'Ширина captcha', '', '120', 0, '120', '', ''),
(51, 'russian', 'Высота captcha', '', '60', 0, '60', '', ''),
(52, 'russian', 'Разброс символов по вертикали', 'Максимальное отклонение символов по вертикали от центра.', '5', 0, '5', '', ''),
(53, 'russian', 'Способ отправки e-mail', '', 'mail', 0, 'mail', 'array(''options''=>array(''php''=>''PHP mail'',''smtp''=>''SMTP'',))', 'Общие настройки'),
(54, 'russian', 'E-mail отправителя', '', 'ss@ss.ru', 0, 'ss@ss.ru', '', ''),
(55, 'russian', 'Важность', '', '3', 0, '3', 'array(\r\n		''options''=>array(1=>''Высочайшая'',''Высокая'',''Обычная'',''Низкая'',''Низшая''),\r\n	)', ''),
(56, 'russian', 'E-mail для ответа', 'В случае, если ответы от пользователей необходимо принимать на другой e-mail, заполните это поле.', '', 0, '', '', ''),
(57, 'russian', 'E-mail для подтверждения о прочтении', '', '', 0, '', '', ''),
(58, 'russian', 'Логин', 'Пользователь', '', 0, '', '', 'Настройки SMTP'),
(59, 'russian', 'Пароль', '', '', 0, '', '', ''),
(60, 'russian', 'Хост', 'Сервер', '', 0, '', '', ''),
(61, 'russian', 'Порт', '', '25', 0, '25', '', ''),
(62, 'russian', 'Редактор по умолчанию', '', 'bb', 0, 'bb', 'array(''eval''=>''return Eleanor::getInstance()->Editor->editors;'')', ''),
(63, 'russian', 'Запрещенные слова', 'Маты и ругательства. Через запятую.', 'slaed, slaed cms, Edmann, DiFor, zigmat, peter911', 0, 'slaed, slaed cms, Edmann, DiFor, zigmat, peter911', '', ''),
(64, 'russian', 'Автозамена запрещенных слов', '', '*Цензура*', 0, '*Цензура*', '', ''),
(65, 'russian', 'Включить защиту от прямых ссылок?', '', 'go', 0, 'go', 'array(''options''=>array(''нет'',''go''=>''Редирект через go.php'',''nofollow''=>''rel="nofollow"'',))', ''),
(66, 'russian', 'Включить автоопределение ссылок в тексте?', 'При включении этой опции, все ссылки опубликованные как текст - будут обработаны как ссылки.', '1', 0, '1', '', ''),
(67, 'russian', 'Логотип RSS', '', 'images/rss.png', 0, 'images/rss.png', 'array(''path''=>''uploads/'',''types''=>array(0=>''jpeg'',1=>''jpg'',2=>''png'',3=>''bmp'',4=>''gif'',),''max_size''=>''307200'',''filename_eval''=>'''',)', ''),
(68, 'russian', 'Порядок сортировки комментариев', '', '1', 0, '1', 'array(\r\n		''options''=>array(1=>''Обратный'',''Прямой''),\r\n	)', ''),
(69, 'russian', 'Комментариев на страницу', '', '10', 0, '10', '', ''),
(70, 'russian', 'Ограничение изменения по времени', 'Введите количество секунд, по истечению которых пользователи не смогут удалять / править свои комментарии. Отсчет времени осуществляется с момента публикации комментария.', '86400', 0, '86400', '', ''),
(71, 'russian', 'Отображать комментарии для', '', 'a:6:{i:0;s:1:"4";i:1;s:1:"1";i:2;s:1:"3";i:3;s:1:"6";i:4;s:1:"5";i:5;s:1:"2";}', 1, 'a:6:{i:0;s:1:"4";i:1;s:1:"1";i:2;s:1:"3";i:3;s:1:"6";i:4;s:1:"5";i:5;s:1:"2";}', 'include Eleanor::$root.''addons/admin/options/groups.php'';', 'Права'),
(72, 'russian', 'Публикация комментариев доступна для', '', 'a:2:{i:0;s:1:"1";i:1;s:1:"2";}', 1, 'a:2:{i:0;s:1:"1";i:1;s:1:"2";}', 'include Eleanor::$root.''addons/admin/options/groups.php'';', ''),
(73, 'russian', 'Включить создание превью для загружаемых изображений?', '', '1', 0, '1', '', 'Превью изображений'),
(74, 'russian', 'Типы файлов для которых создавать превью', '', 'png,jpg,bmp', 0, 'png,jpg,bmp', '', ''),
(75, 'russian', 'Ширина превью', 'Введите 0 для сохранения исходной ширины изображения', '200', 0, '200', '', ''),
(76, 'russian', 'Высота превью', 'Введите 0 для сохранения исходной высоты изображения', '0', 0, '0', '', ''),
(77, 'russian', 'Способ уменьшения изображения', '', 'small', 0, 'small', 'array(\r\n		''options''=>array(\r\n			''cut''=>''Обрезать'',\r\n			''small''=>''Уменьшить'',\r\n			''cutsmall''=>''Обрезать и уменьшить'',\r\n			''smallcut''=>''Уменьшить и обрезать'',\r\n		),\r\n	)', ''),
(78, 'russian', 'Создание превью начать с', '', 'b', 0, 'b', 'array(\r\n		''options''=>array(\r\n			''w''=>''Ширины'',\r\n			''h''=>''Высоты'',\r\n			''b''=>''Наибольшей стороны'',\r\n			''s''=>''Наименьшей стороны'',\r\n		),\r\n	)', ''),
(79, 'russian', 'Включить водяной знак?', 'Наложить водяной знак на загружаемые картинки?', '1', 0, '1', '', 'Настройки водяного знака'),
(80, 'russian', 'Типы файлов для водяного знака', 'На эти типы файлов будет ставиться водяной знак. Указывайте, разделяя запятыми.', 'jpg,jpeg,png,bmp', 0, 'jpg,jpeg,png,bmp', '', ''),
(81, 'russian', 'Прозрачность водяного знака (в процентах от 0 до 100)', '100 - не видно водяного знака', '50', 0, '50', '', ''),
(82, 'russian', 'Положение по вертикали (в процентах от 0 до 100)', '', '50', 0, '50', '', ''),
(83, 'russian', 'Положение по горизонтали (в процентах от 0 до 100)', '', '50', 0, '50', '', ''),
(84, 'russian', 'Файл водяного знака', 'Введите путь к рисунку на сервере, который будет использован в качества водяного знака (например: images/watermrak.jpg). Обратите внимание, что водяной знак не будет применён на изображение если по размерам оно меньше, чем водяной знак. Имеет приоритет над текстом водяного знака.', 'images/watermark.png', 0, 'images/watermark.png', '', ''),
(85, 'russian', 'Текст водяного знака', 'Этот текст будет наложен на изображение в качестве водяного знака, если изображение водяного знака недоступно.', '© Test', 0, '© Test', '', ''),
(86, 'russian', 'Цвет, размер и угол текста водяного знака', 'Задается в формате red,green,blue,size,angle', '1,1,1,15,0', 0, '1,1,1,15,0', '', ''),
(87, 'russian', 'Запретить скачивание с других сайтов?', 'При включении этой опции, при попытке скачать файл будет проверяться адрес страницы, с которой пришел пользователь. Если это будет чужая страница, пользователь не сможет скачать файл.', '1', 0, '1', '', 'Скачивание файлов'),
(88, 'russian', 'Запретить скачивание без сессии?', 'При включении этой опции, пользователь, IP адрес которого не присутствует в списке сессий, не сможет скачать файл.', '1', 0, '1', '', ''),
(89, 'russian', 'Секрет сайта', 'Случайная секретная строка при помощи которой будут подписываться данные для кросс-доменной коммутации.', '5066d63cee1c3', 0, '5066d63cee1c3', '', ''),
(90, 'russian', 'Срок жизни данных кросс-доменной коммутации', 'В секундах.', '100', 0, '100', '', ''),
(91, 'russian', 'Сколько дней хранить черновики?', '', '10', 0, '10', '', ''),
(92, 'russian', 'Интервал автосохранения в секундах', '', '20', 0, '20', '', ''),
(93, 'russian', 'Страницы, выводимые на главной', 'Оставьте пустым для вывода содержания', '', 0, '', 'include Eleanor::$root.''modules/static/optionsg.php''', ''),
(94, 'russian', 'Публикаций на страницу', '', '10', 0, '10', '', 'Основные'),
(95, 'russian', 'Публикаций на страницу в RSS', '', '30', 0, '30', '', ''),
(96, 'russian', 'Добавление новостей пользователями', '', '1', 0, '1', '', ''),
(97, 'russian', 'Выводить содержимое подкатегорий при просмотре категории', '', '1', 0, '1', '', ''),
(98, 'russian', 'Включить ping', 'Уведомление поисковых систем об обновлении на сайте', '1', 0, '1', '', ''),
(99, 'russian', 'Включить рейтинг', '', '1', 0, '1', '', 'Настройки рейтинга'),
(100, 'russian', 'Оценка только при подробном просмотре?', 'Разрешить оценивать публикации только при их подробном просмотре?', '0', 0, '0', '', ''),
(101, 'russian', 'Рейтинг только для пользователей', 'При включении этой опции, выставлять новости оценку смогут только авторизованные пользователи и только 1 раз.', '0', 0, '0', '', ''),
(102, 'russian', 'Период между оцениваниями в днях', 'Если выставлять оценку могут не только пользователи, но и гости, эта опция определяет время, по истечению которого гость сможет вновь выставить оценку.', '3', 0, '3', '', ''),
(103, 'russian', 'Минимальная негативная оценка', 'Значение не может быть выше нуля. Для отключения негативных оценок, введите 0.', '-3', 0, '-3', '', ''),
(104, 'russian', 'Максимальная позитивная оценка', 'Значение не может быть ниже нуля. Для отключения позитивных оценок, введите 0.', '3', 0, '3', '', ''),
(1, 'ukrainian', 'Основний домен', 'Вводиться без приставки http://', 'eleanor.ru', 0, 'eleanor.ru', '', 'Домен'),
(2, 'ukrainian', 'Підтримка паркованих доменів', 'При запуску сайту на паркованому домені', 'redirect', 0, 'redirect', 'array(\r\n		''options''=>array(\r\n			''ignore''=>''Ігнорувати'',\r\n			''redirect''=>''Перенаправити всі посилання на основний домен'',\r\n			''rel''=>''Додати rel canonical'',\r\n		),\r\n	)', ''),
(3, 'ukrainian', 'Кешування сторінок браузером', 'Введіть стандартний термін кешування сторінки у хвилинах. 0 - відключити кешування.', '600', 0, '600', '', 'Оптимізація навантаження'),
(4, 'ukrainian', 'Включати GZIP стиснення?', 'Включення цієї опції дозволить заощадити трафік', '1', 0, '', '', ''),
(5, 'ukrainian', 'Термін зберігання cookie (у днях)', '', '31536000', 0, '31536000', '', 'Cookies'),
(6, 'ukrainian', 'Домен cookie', 'Використовуйте .example.com для глобальних cookie. Зверніть увагу на крапку перед ім''ям домену. Замість "example.com" використовуючи ваше доменне ім''я. Якщо включена підтримка паркованих домено, замість імені домену використовуйте *.', '.*', 0, '.*', '', ''),
(7, 'ukrainian', 'Префікс сookie', 'Дана опція дозволяє уникнути конфліктів, якщо на домені крім системи розташовані також інші скрипти, що використовують cookies.', 'el', 0, 'el', '', ''),
(8, 'ukrainian', 'Група гостей', 'Наділити гостей правами групи...', 'a:1:{i:0;s:1:"3";}', 1, 'a:1:{i:0;s:1:"3";}', 'include Eleanor::$root.''addons/admin/options/groups.php'';', 'Права по замовчуванню'),
(9, 'ukrainian', 'Відслідковувати пошукових роботів?', '', '1', 0, '1', '', ''),
(10, 'ukrainian', 'Група пошукових ботів', 'Наділити пошукових роботів правами групи...', 'a:1:{i:0;s:1:"4";}', 1, 'a:1:{i:0;s:1:"4";}', 'include Eleanor::$root.''addons/admin/options/groups.php'';', ''),
(11, 'ukrainian', 'Список пошукових ботів', 'Тут зберігаються дані про пошукових ботах. Формат вводу: по одному з кожного рядка у вигляді <b>user agent=ім''я бота</ b>', 'a:32:{s:9:"googlebot";s:10:"Google Bot";s:13:"slurp@inktomi";s:7:"Hot Bot";s:11:"archive_org";s:15:"Archive.org Bot";s:10:"Ask Jeeves";s:14:"Ask Jeeves Bot";s:5:"Lycos";s:9:"Lycos Bot";s:9:"WhatUSeek";s:17:"What You Seek Bot";s:11:"ia_archiver";s:15:"IA.Archiver Bot";s:9:"GigaBlast";s:13:"Gigablast Bot";s:7:"Gigabot";s:13:"Gigablast Bot";s:6:"Yandex";s:10:"Yandex Bot";s:6:"Yahoo!";s:9:"Yahoo Bot";s:15:"Yahoo-MMCrawler";s:20:"Yahoo-MM Crawler Bot";s:13:"TurtleScanner";s:18:"Turtle Scanner Bot";s:11:"TurnitinBot";s:12:"Turnitin Bot";s:8:"ZipppBot";s:9:"Zippp Bot";s:12:"StackRambler";s:17:"Stack Rambler Bot";s:4:"oBot";s:4:"oBot";s:7:"rambler";s:11:"Rambler Bot";s:6:"Jetbot";s:7:"Jet Bot";s:8:"NaverBot";s:9:"Naver Bot";s:6:"libwww";s:9:"Punto Bot";s:5:"aport";s:9:"Aport Bot";s:6:"msnbot";s:7:"MSN Bot";s:11:"MnoGoSearch";s:17:"Mno Go Search Bot";s:5:"booch";s:9:"Booch Bot";s:7:"Openbot";s:12:"Openfind Bot";s:7:"scooter";s:13:"Altavista Bot";s:10:"WebCrawler";s:8:"Fast Bot";s:6:"WebZIP";s:10:"WebZIP Bot";s:8:"GetSmart";s:13:"Get Smart Bot";s:11:"grub-client";s:15:"Grub Client Bot";s:7:"Vampire";s:15:"Net Vampire Bot";}', 1, 'a:32:{s:9:"googlebot";s:10:"Google Bot";s:13:"slurp@inktomi";s:7:"Hot Bot";s:11:"archive_org";s:15:"Archive.org Bot";s:10:"Ask Jeeves";s:14:"Ask Jeeves Bot";s:5:"Lycos";s:9:"Lycos Bot";s:9:"WhatUSeek";s:17:"What You Seek Bot";s:11:"ia_archiver";s:15:"IA.Archiver Bot";s:9:"GigaBlast";s:13:"Gigablast Bot";s:7:"Gigabot";s:13:"Gigablast Bot";s:6:"Yandex";s:10:"Yandex Bot";s:6:"Yahoo!";s:9:"Yahoo Bot";s:15:"Yahoo-MMCrawler";s:20:"Yahoo-MM Crawler Bot";s:13:"TurtleScanner";s:18:"Turtle Scanner Bot";s:11:"TurnitinBot";s:12:"Turnitin Bot";s:8:"ZipppBot";s:9:"Zippp Bot";s:12:"StackRambler";s:17:"Stack Rambler Bot";s:4:"oBot";s:4:"oBot";s:7:"rambler";s:11:"Rambler Bot";s:6:"Jetbot";s:7:"Jet Bot";s:8:"NaverBot";s:9:"Naver Bot";s:6:"libwww";s:9:"Punto Bot";s:5:"aport";s:9:"Aport Bot";s:6:"msnbot";s:7:"MSN Bot";s:11:"MnoGoSearch";s:17:"Mno Go Search Bot";s:5:"booch";s:9:"Booch Bot";s:7:"Openbot";s:12:"Openfind Bot";s:7:"scooter";s:13:"Altavista Bot";s:10:"WebCrawler";s:8:"Fast Bot";s:6:"WebZIP";s:10:"WebZIP Bot";s:8:"GetSmart";s:13:"Get Smart Bot";s:11:"grub-client";s:15:"Grub Client Bot";s:7:"Vampire";s:15:"Net Vampire Bot";}', '', ''),
(12, 'ukrainian', 'Увімкнути багатомовну підтримку?', '', '1', 0, '1', '', 'Локалізація'),
(13, 'ukrainian', 'Часовий пояс за замовчуванням', '', 'Europe/Kiev', 0, 'Europe/Kiev', 'include Eleanor::$root.''addons/admin/options/tz.php''', ''),
(14, 'ukrainian', 'Заблоковані IP адреси', 'Кожна адреса - з нового рядка. Допускаються маски виду 87.183 .*.*, а так само діапазони виду 79.224.60.1-79.224.60.255 з підтримкою масок. Щоб вказати унікальну причину бана після введеного IP адреси, поставте = і напишіть причину. Наприклад: 87.183 .*.*=Покидькам тут не місце!', '', 0, '', 'array(''extra''=>array(''style''=>''word-wrap:normal''));', 'Бан по IP'),
(15, 'ukrainian', 'Повідомлення для заблокованих', 'Це повідомлення побачать користувачі, для яких не введена причина.', ':-p', 0, ':-p', '', ''),
(16, 'ukrainian', 'Назва сайту', '', 'Test', 0, 'Test', '', 'Заголовки сайту'),
(17, 'ukrainian', 'Роздільник заголовків', '', ' - ', 0, ' - ', '', ''),
(18, 'ukrainian', 'Опис сайту', '', 'Сайт побудований на системі управління сайтом Eleanor', 0, 'Сайт побудований на системі управління сайтом Eleanor', '', ''),
(19, 'ukrainian', 'Включити статичні посилання?', '', '1', 0, '1', '', 'Налаштування посилань'),
(20, 'ukrainian', 'Транслітерувати статичні посилання?', 'Статичні посилання контенту, а також імена файлів, що завантажуються будуть автоматично транслітеровані.', '0', 0, '', '', ''),
(21, 'ukrainian', 'Роздільник параметрів', 'У посиланні <q>news<b>/</b>category<b>/</b>news<b>/</b>page_1.html</q> роздільником параметрів є коса риска / (слеш).\r\nДля введення допускаються будь-які не літерні символи.', '/', 0, '/', '', ''),
(22, 'ukrainian', 'Роздільник значень', 'У посиланні <q>news<b>/</b>category<b>/</b>news<b>/</b>page_1.html</q> роздільником значень є нижній прочерк _.\r\nДля введення допускаються будь-які не літерні символи.', '_', 0, '_', '', ''),
(23, 'ukrainian', 'Закінчення статичних посилань', 'У посиланні <q>news/category/news/page_1<b>.html</b></q> закінченням є <q>.html</ q>.\r\nЗверніть увагу, що починатися це поле повинне з не літерного символу!', '.html', 0, '.html', '', ''),
(24, 'ukrainian', 'Автозаміна неприпустимих символів у статичних посиланнях', 'Значення не повинно збігатися ні з роздільником параметрів, ні з роздільником значень, ні з закінченням статичних посилань і так само повинно починатися з не літерного символу.', '-', 0, '-', '', ''),
(25, 'ukrainian', 'Модуль без префіксу', 'Посилання цього модуля будуть працювати без вказівки префіксу-ідентифікатора модуля', '2', 0, '2', 'include Eleanor::$root.''addons/admin/options/lfm.php''', ''),
(26, 'ukrainian', 'Вимкнути сайт?', 'Сайт буде доступний тільки групам, для яких включена опція перегляду закритого сайту', '0', 0, '0', '', 'Вимкнення сайту'),
(27, 'ukrainian', 'Причина вимкнення сайту', '', '', 0, '', 'array(''type''=>-1)', ''),
(28, 'ukrainian', 'Інформація про генерацію сторінки', 'Інформація внизу сторінки, що містить швидкість генерації сторінки, кількість використаних запитів до бази даних, статус GZIP стиснення і кількість витраченої пам''яті.', '2', 0, '2', 'array(\r\n		''options''=>array(''Приховати'',''Відображати тільки адміністраторам'',''Відображати всім''),\r\n	)', 'Додаткова інформація'),
(29, 'ukrainian', 'Шаблони на вибір', 'Вкажіть шаблони, які користувачі зможуть вибирати в якості оформлення сайту.', 'a:1:{i:0;s:5:"Uniel";}', 1, 'a:1:{i:0;s:5:"Uniel";}', 'include Eleanor::$root.''addons/admin/options/templates.php''', 'Різне'),
(30, 'ukrainian', 'Посилання особистого кабінету', 'Зверніть увагу, що запис <q>param1=value1<b>&</b>param2=value2</q> некоректний. Коректний запис: <q>param1=value1<b>&amp;</b>param2=value2</q>', '%D1%83%D0%BA%D1%80/%D0%BA%D0%BA%D0%B0%D1%83%D0%BD%D1%82.html', 0, '%D1%83%D0%BA%D1%80/%D0%BA%D0%BA%D0%B0%D1%83%D0%BD%D1%82.html', '', 'Посилання'),
(31, 'ukrainian', 'Посилання на реєстрацію', 'Зверніть увагу, що запис <q>param1=value1<b>&</b>param2=value2</q> некоректний. Коректний запис: <q>param1=value1<b>&amp;</b>param2=value2</q>', '%D1%83%D0%BA%D1%80/%D0%BA%D0%BA%D0%B0%D1%83%D0%BD%D1%82/register', 0, '%D1%83%D0%BA%D1%80/%D0%BA%D0%BA%D0%B0%D1%83%D0%BD%D1%82/register', '', ''),
(32, 'ukrainian', 'Посилання на відновлення пароля', 'Зверніть увагу, що запис <q>param1=value1<b>&</b>param2=value2</q> некоректний. Коректний запис: <q>param1=value1<b>&amp;</b>param2=value2</q>', '%D1%83%D0%BA%D1%80/%D0%BA%D0%BA%D0%B0%D1%83%D0%BD%D1%82/lostpass', 0, '%D1%83%D0%BA%D1%80/%D0%BA%D0%BA%D0%B0%D1%83%D0%BD%D1%82/lostpass', '', ''),
(33, 'ukrainian', 'Тривалість сесій', 'Кількість секунд під час яких користувач вважається онлайн після прояву активності.', 'a:4:{s:10:"LoginAdmin";i:900;s:9:"LoginBase";i:900;s:10:"LoginModer";i:300;s:7:"LoginNo";i:10;}', 1, 'a:4:{s:10:"LoginAdmin";i:900;s:9:"LoginBase";i:900;s:10:"LoginModer";i:300;s:7:"LoginNo";i:10;}', 'include Eleanor::$root.''addons/admin/options/time_online.php''', 'Параметри аутентифікації та авторизації'),
(34, 'ukrainian', 'Тип захисту', '', '1', 0, '', 'array(\r\n		''options''=>array(''Відключено'',''Ліміт спроб за певний час'',''Відображати капчу після вичерпання ліміту спроб входу.''),\r\n	)', 'Захист від підбору паролів'),
(35, 'ukrainian', 'Максимальна кількість невдалих спроб аутентифікації', '', '5', 0, '5', '', ''),
(36, 'ukrainian', 'Максимальний проміжок часу в хвилинах, під час якого допускаються невдалі спроби аутентифікації', 'Приклад: якщо максимальне число невдалих спроб аутентифікації дорівнює 5, а задане значення дорівнює 15, то користувач буде заблокований у разі якщо за останні 15 хвилин було 5 невдалих спроб входу.', '600', 0, '600', '', ''),
(37, 'ukrainian', 'Заблоковані прізвиська', 'Через кому. Допустимі спецсимволи: * - будь-яка послідовність символів,? - будь-який один символ.', '', 0, '', '', 'Блокування'),
(38, 'ukrainian', 'Заблоковані e-mail', 'Через кому. Допустимі спецсимволи: * - будь-яка послідовність символів,? - будь-який один символ.', '', 0, '', '', ''),
(39, 'ukrainian', 'Активація новоствореного користувача', '', '1', 0, '1', 'array(\r\n		''options''=>array(1=>''Не потрібно'',''Через e-mail'',''Вручну адміністратором''),\r\n	)', 'Реєстрація'),
(40, 'ukrainian', 'Термін активації', 'Кількість годин відведених для активації облікового запису.', '86400', 0, '86400', 'array(''type''=>''number'',''extra''=>array(''min''=>1));', ''),
(41, 'ukrainian', 'Як поступати з неактивованими обліковими записами', '', '1', 0, '1', 'array(\r\n		''options''=>array(1=>''Видалити'',''Нічого не робити''),\r\n	)', ''),
(42, 'ukrainian', 'Вимкнути реєстрацію?', '', '0', 0, '0', '', ''),
(43, 'ukrainian', 'Максимальна довжина імені', '', '15', 0, '15', '', ''),
(44, 'ukrainian', 'Мінімальна довжина пароля', '', '7', 0, '7', '', ''),
(45, 'ukrainian', 'Максимальний розмір завантажуваного аватара в KB', '', '307200', 0, '307200', '', 'Профіль'),
(46, 'ukrainian', 'Максимальний розмір аватара', 'Вводити потрібно в форматі: ширина[пробіл]висота.', '100 100', 0, '100 100', '', ''),
(47, 'ukrainian', 'Відновлення пароля', '', '1', 0, '1', 'array(\r\n		''options''=>array(''Заборонено'',''Дозволити ввести новий пароль'',''Згенерувати і вислати пароль на e-mail''),\r\n	)', ''),
(48, 'ukrainian', 'Кількість символів в captcha', '', '5', 0, '5', '', 'Налаштування captcha'),
(49, 'ukrainian', 'Алфавіт captcha', 'Символи що використовуються в captcha (бажано вилучити подібні символи, такі як 0 - цифра і o - буква)', '23456789abcdeghkmnpqsuvxyz', 0, '23456789abcdeghkmnpqsuvxyz', '', ''),
(50, 'ukrainian', 'Ширина captcha', '', '120', 0, '120', '', ''),
(51, 'ukrainian', 'Висота captcha', '', '60', 0, '60', '', ''),
(52, 'ukrainian', 'Розкид символів по вертикалі', 'Максимальне відхилення символів по вертикалі від центру.', '5', 0, '5', '', ''),
(53, 'ukrainian', 'Спосіб відправки e-mail', '', 'mail', 0, 'mail', 'array(''options''=>array(''php''=>''PHP mail'',''smtp''=>''SMTP'',))', 'Загальні налаштування'),
(54, 'ukrainian', 'E-mail відправника', 'С какого ящика будут приходить письма?', 'ss@ss.ru', 0, 'ss@ss.ru', '', ''),
(55, 'ukrainian', 'Важливість', '', '3', 0, '3', 'array(\r\n		''options''=>array(1=>''Найвища'',''Висока'',''Нормальна'',''Низька'',''Найнижча''),\r\n	)', ''),
(56, 'ukrainian', 'E-mail для відповіді', 'У разі, якщо відповіді від користувачів необхідно приймати на інший e-mail, заповніть це поле.', '', 0, '', '', ''),
(57, 'ukrainian', 'E-mail для підтвердження про прочитання', '', '', 0, '', '', ''),
(58, 'ukrainian', 'Логін', 'Користувач', '', 0, '', '', 'Установки SMTP'),
(59, 'ukrainian', 'Пароль', '', '', 0, '', '', ''),
(60, 'ukrainian', 'Хост', 'Сервер', '', 0, '', '', ''),
(61, 'ukrainian', 'Порт', '', '25', 0, '25', '', ''),
(62, 'ukrainian', 'Редактор по замовчуванню', '', 'bb', 0, 'bb', 'array(''eval''=>''return Eleanor::getInstance()->Editor->editors;'')', ''),
(63, 'ukrainian', 'Заборонені слова', 'Мати й лайки. Через кому.', 'slaed, slaed cms, Edmann, DiFor, zigmat, peter911', 0, 'slaed, slaed cms, Edmann, DiFor, zigmat, peter911', '', ''),
(64, 'ukrainian', 'Автозаміна заборонених слів', '', '*Цензура*', 0, '*Цензура*', '', ''),
(65, 'ukrainian', 'Активувати захист від прямих посилань?', '', 'go', 0, 'go', 'array(''options''=>array(''ні'',''go''=>''Редірект через go.php'',''nofollow''=>''rel="nofollow"'',))', ''),
(66, 'ukrainian', 'Включити автовизначення посилань у тексті?', 'При включенні цієї опції, всі посилання опубліковані як текст - будуть оброблені як посилання.', '1', 0, '1', '', ''),
(67, 'ukrainian', 'Логотип RSS', '', 'images/rss.png', 0, 'images/rss.png', 'array(''path''=>''uploads/'',''types''=>array(0=>''jpeg'',1=>''jpg'',2=>''png'',3=>''bmp'',4=>''gif'',),''max_size''=>''307200'',''filename_eval''=>'''',)', ''),
(68, 'ukrainian', 'Порядок сортування коментарів', '', '1', 0, '1', 'array(\r\n		''options''=>array(1=>''Зворотний'',''Прямий''),\r\n	)', ''),
(69, 'ukrainian', 'Коментарів на сторінку', '', '10', 0, '10', '', ''),
(70, 'ukrainian', 'Обмеження зміни за часом', 'Введіть кількість секунд, після завершення яких користувачі не зможуть видаляти / редагувати свої коментарі. Відлік часу здійснюється з моменту публікації коментаря.', '86400', 0, '86400', '', ''),
(71, 'ukrainian', 'Відображати коментарі для', '', 'a:6:{i:0;s:1:"4";i:1;s:1:"1";i:2;s:1:"3";i:3;s:1:"6";i:4;s:1:"5";i:5;s:1:"2";}', 1, 'a:6:{i:0;s:1:"4";i:1;s:1:"1";i:2;s:1:"3";i:3;s:1:"6";i:4;s:1:"5";i:5;s:1:"2";}', 'include Eleanor::$root.''addons/admin/options/groups.php'';', 'Права'),
(72, 'ukrainian', 'Публікація коментарів доступна для', '', 'a:2:{i:0;s:1:"1";i:1;s:1:"2";}', 1, 'a:2:{i:0;s:1:"1";i:1;s:1:"2";}', 'include Eleanor::$root.''addons/admin/options/groups.php'';', ''),
(73, 'ukrainian', 'Включити створення прев''ю для завантажуваних зображень?', '', '1', 0, '1', '', 'Превью зображень'),
(74, 'ukrainian', 'Типи файлів для яких створювати превью', 'Укажите типы файлов для которых будут создаваться превью (через запятую).', 'png,jpg,bmp', 0, 'png,jpg,bmp', '', ''),
(75, 'ukrainian', 'Ширина превью', 'Введіть 0 для збереження вихідної ширини зображення', '200', 0, '200', '', ''),
(76, 'ukrainian', 'Висота прев''ю', 'Введіть 0 для збереження вихідної висоти зображення', '0', 0, '0', '', ''),
(77, 'ukrainian', 'Спосіб зменшення зображення', '', 'small', 0, 'small', 'array(\r\n		''options''=>array(\r\n			''cut''=>''Обрізати'',\r\n			''small''=>''Зменшити'',\r\n			''cutsmall''=>''Обрізати та зменшити'',\r\n			''smallcut''=>''Зменшити та обрізати'',\r\n		),\r\n	)', ''),
(78, 'ukrainian', 'Створення превью почати з', '', 'b', 0, 'b', 'array(\r\n		''options''=>array(\r\n			''w''=>''Ширини'',\r\n			''h''=>''Висоти'',\r\n			''b''=>''Найбільшої сторони'',\r\n			''s''=>''Найменшої сторони'',\r\n		),\r\n	)', ''),
(79, 'ukrainian', 'Включити водяний знак?', 'Накласти водяний знак на завантажувані картинки?', '1', 0, '1', '', 'Настройки ватермарка'),
(80, 'ukrainian', 'Типи файлів для водяного знака', 'На ці типи файлів буде ставитися водяний знак. Вказуйте, розділяючи комами.', 'jpg,jpeg,png,bmp', 0, 'jpg,jpeg,png,bmp', '', ''),
(81, 'ukrainian', 'Прозорість водяного знаку (у відсотках від 0 до 100)', '100 - не видно водяного знаку', '50', 0, '50', '', ''),
(82, 'ukrainian', 'Положення по вертикалі (у відсотках від 0 до 100)', '', '50', 0, '50', '', ''),
(83, 'ukrainian', 'Положення по горизонталі (у відсотках від 0 до 100)', '', '50', 0, '50', '', ''),
(84, 'ukrainian', 'Файл водяного знаку', 'Введіть шлях до малюнка на сервері, який буде використаний в якості водяного знака (наприклад: images / watermrak.jpg). Зверніть увагу, що водяний знак не буде застосований на зображення якщо за розмірами вона менша, ніж водяний знак. Має пріоритет над текстом водяного знака.', 'images/watermark.png', 0, 'images/watermark.png', '', ''),
(85, 'ukrainian', 'Текст водяного знака', 'Цей текст буде накладено на зображення в якості водяного знака, якщо зображення водяного знака недоступне.', '© Test', 0, '© Test', '', ''),
(86, 'ukrainian', 'Колір, розмір і кут тексту водяного знака', 'Задається в форматі red, green, blue, size, angle', '1,1,1,15,0', 0, '1,1,1,15,0', '', ''),
(87, 'ukrainian', 'Заборонити скачування з інших сайтів?', 'При включенні цієї опції, при спробі завантажити файл буде перевірятися адресу сторінки, з якою прийшов користувач. Якщо це буде чужа сторінка, користувач не зможе завантажити файл.', '1', 0, '1', '', 'Завантаження файлів'),
(88, 'ukrainian', 'Заборонити скачування без сесії?', 'При включенні цієї опції, користувач, IP-адреса якого не присутній у списку сесій, не зможе завантажити файл.', '1', 0, '1', '', ''),
(89, 'ukrainian', 'Секрет сайту', 'Випадковий секретний рядок за допомогою якого будуть підписуватися дані для міждоменної комутації.', '5066d63cee1c3', 0, '5066d63cee1c3', '', ''),
(90, 'ukrainian', 'Термін життя даних крос-доменної комутації', 'У секундах.', '100', 0, '100', '', ''),
(91, 'ukrainian', 'Скільки днів зберігати чернетки?', '', '10', 0, '10', '', ''),
(92, 'ukrainian', 'Інтервал автозбереження в секундах', '', '20', 0, '20', '', ''),
(93, 'ukrainian', 'Сторінки, що виводиться на головній', 'Залиште пустим для виведення змісту', '', 0, '', 'include Eleanor::$root.''modules/static/optionsg.php''', ''),
(94, 'ukrainian', 'Публікацій на сторінку', '', '10', 0, '10', '', 'Загальні'),
(95, 'ukrainian', 'Публікацій на сторінку в RSS', '', '30', 0, '30', '', ''),
(96, 'ukrainian', 'Додавання новин користувачами', '', '1', 0, '1', '', ''),
(97, 'ukrainian', 'Виводити вміст підкатегорій при перегляді категорії', '', '1', 0, '1', '', ''),
(98, 'ukrainian', 'Включити ping', 'Повідомлення пошукових систем про оновлення на сайті', '1', 0, '1', '', ''),
(99, 'ukrainian', 'Включити рейтинг', '', '1', 0, '1', '', 'Настройки рейтингу'),
(100, 'ukrainian', 'Оцінка тільки при детальному перегляді?', 'Дозволити оцінювати публікації тільки при їх детальному перегляді?', '0', 0, '0', '', ''),
(101, 'ukrainian', 'Рейтинг тільки для користувачів', 'При включенні цієї опції, виставляти новини оцінку зможуть лише авторизовані користувачі і лише 1 раз.', '0', 0, '0', '', ''),
(102, 'ukrainian', 'Період між оцінювання у днях', 'Якщо виставляти оцінку можуть не лише користувачі, але й гості, ця опція визначає час, по закінченню якого гість зможе знову виставити оцінку.', '3', 0, '3', '', ''),
(103, 'ukrainian', 'Мінімальна негативна оцінка', 'Значення не може бути більше нуля. Для відключення негативних оцінок, введіть 0.', '-3', 0, '-3', '', ''),
(104, 'ukrainian', 'Максимальна позитивна оцінка', 'Значення не може бути нижче нуля. Для відключення позитивних оцінок, введіть 0', '3', 0, '3', '', ''),
(1, 'english', 'Primary domain', 'Enter without prefix http://', 'eleanor.ru', 0, 'eleanor.ru', '', 'Domain'),
(2, 'english', 'Support for parked domains', 'When site running on a parked domain', 'redirect', 0, 'redirect', 'array(\r\n		''options''=>array(\r\n			''ignore''=>''Ignore'',\r\n			''redirect''=>''Redirect all links to the primary domain'',\r\n			''rel''=>''Add rel canonical'',\r\n		),\r\n	)', ''),
(3, 'english', 'Browser page caching', 'Enter the standard term caching pages in minutes. 0 - disable caching.', '600', 0, '600', '', 'Optimizing workload'),
(4, 'english', 'Enamble GZIP compression?', 'Enabling this option will save bandwidth', '1', 0, '', '', ''),
(5, 'english', 'Cookie lifetime (in days)', '', '31536000', 0, '31536000', '', 'Cookies'),
(6, 'english', 'Cookie domain', 'Use .example.com for the global cookie. Note the dot before the domain name. Instead of "example.com" use your domain name. If enabled parked domain names, instead of the domain name use *.', '.*', 0, '.*', '', ''),
(7, 'english', 'Cookie prefix', 'This option allows you to avoid conflicts if a domain other than the system are located and other scripts that use cookies.', 'el', 0, 'el', '', ''),
(8, 'english', 'Guests group', 'Give guest the rights of group...', 'a:1:{i:0;s:1:"3";}', 1, 'a:1:{i:0;s:1:"3";}', 'include Eleanor::$root.''addons/admin/options/groups.php'';', 'Permissions by default'),
(9, 'english', 'Track search engine bots?', '', '1', 0, '1', '', ''),
(10, 'english', 'Search engine bots group', 'Give the search bots rights of group...', 'a:1:{i:0;s:1:"4";}', 1, 'a:1:{i:0;s:1:"4";}', 'include Eleanor::$root.''addons/admin/options/groups.php'';', ''),
(11, 'english', 'List of search engine bots', 'Here, the data is stored on the search bots. Input format: one on each line in the form <b>user agent=bot</ b>.', 'a:32:{s:9:"googlebot";s:10:"Google Bot";s:13:"slurp@inktomi";s:7:"Hot Bot";s:11:"archive_org";s:15:"Archive.org Bot";s:10:"Ask Jeeves";s:14:"Ask Jeeves Bot";s:5:"Lycos";s:9:"Lycos Bot";s:9:"WhatUSeek";s:17:"What You Seek Bot";s:11:"ia_archiver";s:15:"IA.Archiver Bot";s:9:"GigaBlast";s:13:"Gigablast Bot";s:7:"Gigabot";s:13:"Gigablast Bot";s:6:"Yandex";s:10:"Yandex Bot";s:6:"Yahoo!";s:9:"Yahoo Bot";s:15:"Yahoo-MMCrawler";s:20:"Yahoo-MM Crawler Bot";s:13:"TurtleScanner";s:18:"Turtle Scanner Bot";s:11:"TurnitinBot";s:12:"Turnitin Bot";s:8:"ZipppBot";s:9:"Zippp Bot";s:12:"StackRambler";s:17:"Stack Rambler Bot";s:4:"oBot";s:4:"oBot";s:7:"rambler";s:11:"Rambler Bot";s:6:"Jetbot";s:7:"Jet Bot";s:8:"NaverBot";s:9:"Naver Bot";s:6:"libwww";s:9:"Punto Bot";s:5:"aport";s:9:"Aport Bot";s:6:"msnbot";s:7:"MSN Bot";s:11:"MnoGoSearch";s:17:"Mno Go Search Bot";s:5:"booch";s:9:"Booch Bot";s:7:"Openbot";s:12:"Openfind Bot";s:7:"scooter";s:13:"Altavista Bot";s:10:"WebCrawler";s:8:"Fast Bot";s:6:"WebZIP";s:10:"WebZIP Bot";s:8:"GetSmart";s:13:"Get Smart Bot";s:11:"grub-client";s:15:"Grub Client Bot";s:7:"Vampire";s:15:"Net Vampire Bot";}', 1, 'a:32:{s:9:"googlebot";s:10:"Google Bot";s:13:"slurp@inktomi";s:7:"Hot Bot";s:11:"archive_org";s:15:"Archive.org Bot";s:10:"Ask Jeeves";s:14:"Ask Jeeves Bot";s:5:"Lycos";s:9:"Lycos Bot";s:9:"WhatUSeek";s:17:"What You Seek Bot";s:11:"ia_archiver";s:15:"IA.Archiver Bot";s:9:"GigaBlast";s:13:"Gigablast Bot";s:7:"Gigabot";s:13:"Gigablast Bot";s:6:"Yandex";s:10:"Yandex Bot";s:6:"Yahoo!";s:9:"Yahoo Bot";s:15:"Yahoo-MMCrawler";s:20:"Yahoo-MM Crawler Bot";s:13:"TurtleScanner";s:18:"Turtle Scanner Bot";s:11:"TurnitinBot";s:12:"Turnitin Bot";s:8:"ZipppBot";s:9:"Zippp Bot";s:12:"StackRambler";s:17:"Stack Rambler Bot";s:4:"oBot";s:4:"oBot";s:7:"rambler";s:11:"Rambler Bot";s:6:"Jetbot";s:7:"Jet Bot";s:8:"NaverBot";s:9:"Naver Bot";s:6:"libwww";s:9:"Punto Bot";s:5:"aport";s:9:"Aport Bot";s:6:"msnbot";s:7:"MSN Bot";s:11:"MnoGoSearch";s:17:"Mno Go Search Bot";s:5:"booch";s:9:"Booch Bot";s:7:"Openbot";s:12:"Openfind Bot";s:7:"scooter";s:13:"Altavista Bot";s:10:"WebCrawler";s:8:"Fast Bot";s:6:"WebZIP";s:10:"WebZIP Bot";s:8:"GetSmart";s:13:"Get Smart Bot";s:11:"grub-client";s:15:"Grub Client Bot";s:7:"Vampire";s:15:"Net Vampire Bot";}', '', ''),
(12, 'english', 'Enable multilingual support?', '', '1', 0, '1', '', 'Localization'),
(13, 'english', 'Timezone by default', '', 'Europe/Kiev', 0, 'Europe/Kiev', 'include Eleanor::$root.''addons/admin/options/tz.php''', ''),
(14, 'english', 'Blocked IP addresses', 'Each address - with a new line. Wildcards like 87.183.*.* are enabled, where * is any value. That would indicate a unique reason for the ban imposed after the IP address, put "=" and write the reason. For example:<br />87.183.*.*=Fuck you!', '', 0, '', 'array(''extra''=>array(''style''=>''word-wrap:normal''));', 'Blocking by IP'),
(15, 'english', 'Message to the blocked', 'This message will appear to users that do not enter a reason.', ':-p', 0, ':-p', '', ''),
(16, 'english', 'Site name', '', 'Test', 0, 'Test', '', 'Site headers'),
(17, 'english', 'Separator titles', '', ' - ', 0, ' - ', '', ''),
(18, 'english', 'Site description', '', 'The site is built on a content management system Eleanor', 0, 'The site is built on a content management system Eleanor', '', ''),
(19, 'english', 'Enable static links?', '', '1', 0, '1', '', 'Links options'),
(20, 'english', 'Transliterate static links?', 'Static links content and the names of uploaded files will be automatically transliterated.', '0', 0, '', '', ''),
(21, 'english', 'Delimiter parameters', 'In link <q>news<b>/</b>category<b>/</b>news<b>/</b>page_1.html</q>  delimiter parameters is / (slash).\r\nAllowed to enter any non-alphabetic characters.', '/', 0, '/', '', ''),
(22, 'english', 'Delimiter values', 'In exile, <q>news/category/news/page<b>_</b>1.html</q> separator value is lower dash _.\r\nAllowed to enter any non-alphabetic characters.', '_', 0, '_', '', ''),
(23, 'english', 'End of static links', 'In link <q>news/category/news/page_1<b>.html</b></q> ending is <q>.html</ q>.\r\nNote that this field should begin with an alphabetic character is not!', '.html', 0, '.html', '', ''),
(24, 'english', 'Autocorrect invalid characters in static links', 'Value should not coincide with delimiter parameters or delimited values, or with the end of static links and the same should not begin with an alphabetic character.', '-', 0, '-', '', ''),
(25, 'english', 'Module without prefix', 'Links of this module will work without module prefix-identifier', '2', 0, '2', 'include Eleanor::$root.''addons/admin/options/lfm.php''', ''),
(26, 'english', 'Turn off the site?', 'Site will be available to groups for which the option view site closing', '0', 0, '0', '', 'Turning site off'),
(27, 'english', 'The reason for the turning off the site', '', '', 0, '', 'array(''type''=>-1)', ''),
(28, 'english', 'Information about the generation of page', 'Information at the bottom of the page containing the speed of page generation, the number of used database queries, GZIP compression status and number of memory consumed.', '2', 0, '2', 'array(\r\n		''options''=>array(''Hide'',''Display only for administrators'',''Display for all''),\r\n	)', 'Addon information'),
(29, 'english', 'Templates to choose', 'Specify a templates that users can choose as a site design.', 'a:1:{i:0;s:5:"Uniel";}', 1, 'a:1:{i:0;s:5:"Uniel";}', 'include Eleanor::$root.''addons/admin/options/templates.php''', 'Others'),
(30, 'english', 'Link to personal cabinet', 'Please note that the record <q>param1=value1<b>&</b>param2=value2</q> is incorrect. Correct record is <q>param1=value1<b>&amp;</b>param2=value2</q>', 'eng/account.html', 0, 'eng/account.html', '', 'Links'),
(31, 'english', 'Link to registration', 'Please note that the record <q>param1=value1<b>&</b>param2=value2</q> is incorrect. Correct record is <q>param1=value1<b>&amp;</b>param2=value2</q>', 'eng/account/register', 0, 'eng/account/register', '', ''),
(32, 'english', 'Link to password recovery', 'Please note that the record <q>param1=value1<b>&</b>param2=value2</q> is incorrect. Correct record is <q>param1=value1<b>&amp;</b>param2=value2</q>', 'eng/account/lostpass', 0, 'eng/account/lostpass', '', ''),
(33, 'english', 'Duration of sessions', 'Number of seconds during which user considered as online after his last activity.', 'a:4:{s:10:"LoginAdmin";i:900;s:9:"LoginBase";i:900;s:10:"LoginModer";i:300;s:7:"LoginNo";i:10;}', 1, 'a:4:{s:10:"LoginAdmin";i:900;s:9:"LoginBase";i:900;s:10:"LoginModer";i:300;s:7:"LoginNo";i:10;}', 'include Eleanor::$root.''addons/admin/options/time_online.php''', 'The authentication and authorization'),
(34, 'english', 'Protection type', '', '1', 0, '', 'array(\r\n		''options''=>array(''Disabled'',''Limit of attempts within a certain time'',''Display the captcha, after exhausting the limit of login attempts''),\r\n	);', 'Protection against guessing password'),
(35, 'english', 'The maximum number of unsuccessful authentication attempts', '', '5', 0, '5', '', ''),
(36, 'english', 'The maximum amount of time in minutes, during which allowed failed authentication attempts', 'Example: If the maximum number of failed authentication attempts is 5, and the set value is 15, the user will be blocked if the last 15 minutes were 5 failed login attempts.', '600', 0, '600', '', ''),
(37, 'english', 'Blocked nicknames', 'Separated by commas. Allowable special characters: * - any sequence of characters,? - any one character.', '', 0, '', '', 'Bans'),
(38, 'english', 'Blocked e-mail', 'Separated by commas. Allowable special characters: * - any sequence of characters,? - any one character.', '', 0, '', '', ''),
(39, 'english', 'Activation of newly created user', '', '1', 0, '1', 'array(\r\n		''options''=>array(1=>''Not required'',''By e-mail'',''Manually by an administrator''),\r\n	)', 'Register'),
(40, 'english', 'Activation term', 'The number of hours allotted to activate account.', '86400', 0, '86400', 'array(''type''=>''number'',''extra''=>array(''min''=>1));', ''),
(41, 'english', 'How to deal with nonactivated accounts', '', '1', 0, '1', 'array(\r\n		''options''=>array(1=>''Delete'',''Nothing''),\r\n	)', ''),
(42, 'english', 'Disable registration?', '', '0', 0, '0', '', ''),
(43, 'english', 'The maximum length of nickname', '', '15', 0, '15', '', ''),
(44, 'english', 'The minimum length of password', '', '7', 0, '7', '', ''),
(45, 'english', 'Maximum size of uploaded avatars in KB', '', '307200', 0, '307200', '', 'Profile'),
(46, 'english', 'Maximum size of avatar', 'Need to enter in the format: width[space]height.', '100 100', 0, '100 100', '', ''),
(47, 'english', 'Password recovery', '', '1', 0, '1', 'array(\r\n		''options''=>array(''Disabled'',''Allow enter a new password'',''Generate and send the password to the e-mail''),\r\n	)', ''),
(48, 'english', 'Number of characters in captcha', '', '5', 0, '5', '', 'Captcha options'),
(49, 'english', 'Captcha alphabet', 'Symbols used in the captcha (preferably exclude similar characters like 0 - number and o - letter)', '23456789abcdeghkmnpqsuvxyz', 0, '23456789abcdeghkmnpqsuvxyz', '', ''),
(50, 'english', 'Сaptcha width', '', '120', 0, '120', '', ''),
(51, 'english', 'Captcha height', '', '60', 0, '60', '', ''),
(52, 'english', 'The scatter symbols on the vertical', 'The maximum deviation of the symbols on the vertical line from the center.', '5', 0, '5', '', ''),
(53, 'english', 'Way to send e-mail', '', 'mail', 0, 'mail', 'array(''options''=>array(''php''=>''PHP mail'',''smtp''=>''SMTP'',))', 'General settiongs'),
(54, 'english', 'Sender e-mail', 'From what email letters will send?', 'ss@ss.ru', 0, 'ss@ss.ru', '', 'Общие настройки'),
(55, 'english', 'Importance', '', '3', 0, '3', 'array(\r\n		''options''=>array(1=>''Highest'',''High'',''Normal'',''Low'',''Lowest''),\r\n	);', ''),
(56, 'english', 'E-mail for response', 'If the response from the user should be taken to another e-mail, fill out this field.', '', 0, '', '', ''),
(57, 'english', 'E-mail to confirm a read', '', '', 0, '', '', ''),
(58, 'english', 'Login', 'User', '', 0, '', '', 'SMTP settings'),
(59, 'english', 'Password', '', '', 0, '', '', ''),
(60, 'english', 'Host', 'Server', '', 0, '', '', ''),
(61, 'english', 'Port', '', '25', 0, '25', '', ''),
(62, 'english', 'Editor by default', '', 'bb', 0, 'bb', 'array(''eval''=>''return Eleanor::getInstance()->Editor->editors;'')', ''),
(63, 'english', 'Swear words', 'Mats and abuse. Separated by commas.', 'slaed, slaed cms, Edmann, DiFor, zigmat, peter911', 0, 'slaed, slaed cms, Edmann, DiFor, zigmat, peter911', '', ''),
(64, 'english', 'Autocorrect banned words', '', '*Censorship*', 0, '*Censorship*', '', ''),
(65, 'english', 'Enable protection from direct links?', '', 'bb', 0, 'bb', 'array(''options''=>array(''no'',''go''=>''Redirect via go.php'',''nofollow''=>''rel="nofollow"'',))', ''),
(66, 'english', 'Enable autoparse links in the text?', 'If you enable this option, all links published as text - will be treated as links.', '1', 0, '1', '', ''),
(67, 'english', 'RSS logo', '', 'images/rss.png', 0, 'images/rss.png', 'array(''path''=>''uploads/'',''types''=>array(0=>''jpeg'',1=>''jpg'',2=>''png'',3=>''bmp'',4=>''gif'',),''max_size''=>''307200'',''filename_eval''=>'''',)', ''),
(68, 'english', 'Order displaying comments', '', '1', 0, '1', 'array(\r\n		''options''=>array(1=>''Reverse'',''Direct''),\r\n	)', ''),
(69, 'english', 'Comments per page', '', '10', 0, '10', '', ''),
(70, 'english', 'Limitation of time changes', 'Enter the number of seconds after which users can not delete / edit your comments. The countdown is carried out since the publication of comments.', '86400', 0, '86400', '', ''),
(71, 'english', 'Display comments for', '', 'a:6:{i:0;s:1:"4";i:1;s:1:"1";i:2;s:1:"3";i:3;s:1:"6";i:4;s:1:"5";i:5;s:1:"2";}', 1, 'a:6:{i:0;s:1:"4";i:1;s:1:"1";i:2;s:1:"3";i:3;s:1:"6";i:4;s:1:"5";i:5;s:1:"2";}', 'include Eleanor::$root.''addons/admin/options/groups.php'';', 'Rights'),
(72, 'english', 'Post comments available for', '', 'a:2:{i:0;s:1:"1";i:1;s:1:"2";}', 1, 'a:2:{i:0;s:1:"1";i:1;s:1:"2";}', 'include Eleanor::$root.''addons/admin/options/groups.php'';', ''),
(73, 'english', 'Enable the creation of thumbs for uploaded images?', '', '1', 0, '1', '', 'Preview images'),
(74, 'english', 'File types for which to create thumbs', 'Specify the file types for which to create a preview (separated by comma).', 'png,jpg,bmp', 0, 'png,jpg,bmp', '', ''),
(75, 'english', 'Thumb width', 'Enter 0 to keep the original width of the image', '200', 0, '200', '', ''),
(76, 'english', 'Height preview', 'Enter 0 to keep the original height of the image', '0', 0, '0', '', ''),
(77, 'english', 'Method of reducing the image', '', 'small', 0, 'small', 'array(\r\n		''options''=>array(\r\n			''cut''=>''Crop'',\r\n			''small''=>''Reduce'',\r\n			''cutsmall''=>''Crop and reduce'',\r\n			''smallcut''=>''Reduce and crop'',\r\n		),\r\n	)', ''),
(78, 'english', 'Creating a thumb begin with', '', 'b', 0, 'b', 'array(\r\n		''options''=>array(\r\n			''w''=>''Width'',\r\n			''h''=>''Height'',\r\n			''b''=>''Biggest side'',\r\n			''s''=>''Smallest side'',\r\n		),\r\n	)', ''),
(79, 'english', 'Enable a watermark?', 'Apply a watermark to your uploaded images?', '1', 0, '1', '', 'Настройки ватермарка'),
(80, 'english', 'Filetypes for watermark', 'These types of files will be put watermark. Specify, separated by commas.', 'jpg,jpeg,png,bmp', 0, 'jpg,jpeg,png,bmp', '', ''),
(81, 'english', 'Transparency of the watermark (as a percentage from 0 to 100)', '100 - not visible watermark', '50', 0, '50', '', ''),
(82, 'english', 'Vertical position (as a percentage from 0 to 100)', '', '50', 0, '50', '', ''),
(83, 'english', 'Horizontal position (as a percentage from 0 to 100)', '', '50', 0, '50', '', ''),
(84, 'english', 'File of the watermark', 'Enter the path to the picture on the server, which will be used as a watermark (eg: images / watermrak.jpg). Please note that the watermark will not be applied to the image if the size is less than the watermark. Takes precedence over the text watermark.', 'images/watermark.png', 0, 'images/watermark.png', '', ''),
(85, 'english', 'Text watermark', 'This text will be superimposed on the image as a watermark, if the watermark image is not available.', '© Test', 0, '© Test', '', ''),
(86, 'english', 'Color, size and angle of text watermark', 'Given in the format of red, green, blue, size, angle', '1,1,1,15,0', 0, '1,1,1,15,0', '', ''),
(87, 'english', 'Prohibit downloads from other sites?', 'When this option when you try to download the file will be checked to indicate the address to which the user came from. If it is someone else''s page, the user can not download the file.', '1', 0, '1', '', 'Downloading files'),
(88, 'english', 'Prohibit downloading without session?', 'When this option is enabled, the user, IP address is not on the list of sessions will not be able to download the file.', '1', 0, '1', '', ''),
(89, 'english', 'Site secret', 'A random secret string with which to sign the data for cross-domain switching.', '5066d63cee1c3', 0, '5066d63cee1c3', '', ''),
(90, 'english', 'The life of these cross-domain switching', 'In seconds.', '100', 0, '100', '', ''),
(91, 'english', 'Days to keep drafts?', '', '10', 0, '10', '', ''),
(92, 'english', 'Autosave interval in seconds', '', '20', 0, '20', '', ''),
(93, 'english', 'The pages displayed on the main', 'Leave empty to display contents', '', 0, '', 'include Eleanor::$root.''modules/static/optionsg.php''', ''),
(94, 'english', 'Publications per page', '', '10', 0, '10', '', 'General'),
(95, 'english', 'Publications per page in RSS', '', '30', 0, '30', '', ''),
(96, 'english', 'Adding news by users', '', '1', 0, '1', '', ''),
(97, 'english', 'Display the contents of subcategories when viewing category', '', '1', 0, '1', '', ''),
(98, 'english', 'Enable ping', 'Notification search engines about updating on the site', '1', 0, '1', '', ''),
(99, 'english', 'Enable rating', '', '1', 0, '1', '', 'Rating options'),
(100, 'english', 'Score only in the detailed view?', 'Allow to assess publication only when they are detailed viewing?', '0', 0, '0', '', ''),
(101, 'english', 'Rating users only', 'When this option is on, rate news can only authorized users and only 1 time.', '0', 0, '0', '', ''),
(102, 'english', 'Period between marks in days', 'If rate can not only users but also the guests, this option specifies the time after which guests will be able to remark.', '3', 0, '3', '', ''),
(103, 'english', 'Low negative mark', 'Value can not be greater than zero. To turn off the negative marks, enter 0.', '-3', 0, '-3', '', ''),
(104, 'english', 'The maximum positive mark', 'Value can not be below zero. To disable the positive ratings, please enter 0.', '3', 0, '3', '', '');
SQL
);

		Eleanor::$Db->Query('UPDATE `'.P.'config_l` `cl`, `tmp_config_l` `tl`, `'.P.'config` `c`, `tmp_config` `t` SET `cl`.`value`=`tl`.`value`, `cl`.`serialized`=`tl`.`serialized`, `cl`.`default`=`tl`.`default` WHERE `c`.`id`=`cl`.`id` AND `t`.`id`=`tl`.`id` AND `cl`.`language`=`tl`.`language` AND `c`.`name`=`t`.`name` AND `c`.`id`!=35');

		Eleanor::$Db->Query('ALTER TABLE `'.P.'config_groups` CHANGE `position` `pos` SMALLINT UNSIGNED NOT NULL');
		Eleanor::$Db->Query('ALTER TABLE `'.P.'errors_l` CHANGE `url` `uri` VARCHAR(100) NOT NULL, DROP INDEX `url`, ADD INDEX `uri` ( `uri` )');
		Eleanor::$Db->Query('ALTER TABLE `'.P.'modules` DROP `user_groups`');
		Eleanor::$Db->Query('ALTER TABLE `'.P.'news_categories_l` CHANGE `url` `uri` VARCHAR(100) NOT NULL');
		Eleanor::$Db->Query('ALTER TABLE `'.P.'news_l` ADD `announcement` TEXT NOT NULL AFTER `title`, CHANGE `url` `uri` VARCHAR(100) NOT NULL,  DROP INDEX `url`, ADD INDEX `uri` ( `uri` ), DROP INDEX `title`, ADD FULLTEXT `title` (`title`, `announcement`, `text`)');
		Eleanor::$Db->Query('ALTER TABLE `'.P.'news_tags` CHANGE `news` `cnt` SMALLINT UNSIGNED NOT NULL, DROP INDEX `news`, ADD INDEX `cnt`(`cnt`)');

		Eleanor::$Db->Query('RENAME TABLE `'.P.'news_nt` TO `a_news_rt`');
		$cr=Eleanor::$Db->Query('SHOW CREATE TABLE `'.P.'news_rt`')->fetch_row();
		preg_match('#CONSTRAINT `('.P.'news_rt_ibfk_\d+)` FOREIGN KEY \(`news`\)#',$cr[1],$cr);

		Eleanor::$Db->Query('ALTER TABLE `'.P.'news_rt` DROP FOREIGN KEY `'.$cr[1].'`, CHANGE `news` `id` MEDIUMINT(8) UNSIGNED NOT NULL, ADD FOREIGN KEY ( `id` ) REFERENCES `'.P.'news`(`id`) ON DELETE CASCADE ON UPDATE CASCADE');

		Eleanor::$Db->Query('UPDATE `'.P.'news_l` SET `announcement`=`text`, `text`=\'\' WHERE LOCATE(\'[_separator_]\',`text`)=0');
		Eleanor::$Db->Query('UPDATE `'.P.'news_l` SET `announcement`=LEFT(`text`,LOCATE(\'[_separator_]\',`text`)-1), `text`=SUBSTRING(`text`,LOCATE(\'[_separator_]\',`text`)+13) WHERE LOCATE(\'[_separator_]\',`text`)!=0');

		Eleanor::$Db->Query('ALTER TABLE `'.P.'users_extra` CHANGE `vkontakte` `vk` VARCHAR( 40 ) NOT NULL');
		Eleanor::$Db->Query('RENAME TABLE `'.P.'users_loginza` TO `'.P.'users_external_auth`');
		Eleanor::$Db->Query('ALTER TABLE `'.P.'users` CHANGE `ban_date` `banned_until` TIMESTAMP NOT NULL DEFAULT \'0000-00-00 00:00:00\'');
		Eleanor::$Db->Query('ALTER TABLE `'.P.'blocks_groups` CHANGE `addon` `extra` TEXT NOT NULL');
		Eleanor::$Db->Query('ALTER TABLE `'.P.'sessions` CHANGE `addon` `extra` VARCHAR(100) NOT NULL');	}
}