<?php
return array(
	#For Classes/UserNews.php & Classes/UserNewsCorrect.php
	'all'=>'All news',
	'add'=>'Add news',
	'tags_'=>'Tags: %s',
	'comments_'=>function($n,$l){return$l.($n==1 ? ' comment'  : ' comments');},
	'published_'=>'Published: %s',
	'category_'=>'Category: %s',
	'publisher_'=>'Published by: %s',
	'reads_'=>'Views: %s',
	'readmore'=>'Read more',
	'notag'=>'Sorry, no news with tag &quot;%s&quot;.',
	'lookfor'=>'News search',
	'find'=>'Find',
	'what'=>'What',
	'or'=>'AND',
	'and'=>'OR',
	'activated'=>'Activated',
	'deactivated'=>'Deactivated',
	'notfound'=>'Upon request, nothing found',
	'swhere'=>'Where',
	'ta'=>'Title and announcement',
	'tat'=>'Title, announcement and text',
	'sortby'=>'Sort results by',
	'sdate'=>'Date',
	'srel'=>'Relevance',
	'modadd'=>'News &quot;%s&quot; successfully added. After being moderated, it might become available.',
	'modedit'=>'News &quot;%s&quot; successfully edited. After being moderated, it might become available.',
	'nomodadd'=>'News &quot;%s&quot; successfully added.',
	'nomodedit'=>'News &quot;%s&quot; successfully edited.',
	'statusadd'=>'You have successfully added news &quot;%s&quot;, but did not activate it for viewing by other users.',
	'statusedit'=>'You have successfully edited the news &quot;%s&quot;, but did not activate it for viewing by other users.',
	'goto'=>'Go to: %s',
	'pagewg'=>'page, where you came from',
	'submit_del'=>'Do you really want to delete news &quot;%s&quot;?',
	'deleting'=>'You have successfully removed news &quot;%s&quot;',
	'waitmod'=>'Waiting for moderation',

	'save'=>'Save news',
	'nodraft'=>'Without draft',
	'title'=>'Title',
	'maincat'=>'Main category',
	'tags'=>'Tags',
	'ftags_'=>'Enter a comma-separated',
	'announcement'=>'Анонс',
	'announcement_'=>'Announcement of news is as annotation to book - must convince reader to read it',
	'text'=>'News text',
	'show_sokr'=>'Display a brief overview?',
	'show_sokr_'=>'for detailed viewing',
	'show_detail'=>'Show the link &quot;read more&quot;?',
	'show_detail_'=>'in the absence of detailed',
	'set_for_langs'=>'Set for languages',
	'captcha'=>'Security code',
	'captcha_'=>'type the characters you see',
	'status'=>'Status',
	'active'=>'Activate',
	'blocked'=>'Deactivate',
	'general'=>'General',
	'voting'=>'Voting',
	'enddate'=>'Available until',
	'enddate_'=>'With the arrival of this date, the news is no longer displayed on the site',
	'author'=>'Your name',
	'WRONG_CAPTCHA'=>'Security code is entered with error.',
);