<?php
$CFG=array(
'charsets'=>'cp1251 utf8 latin1',
'lang'=>'auto',
'time_web'=>'600',
'time_cron'=>'600',
'backup_path'=>'backup/',
'backup_url'=>'backup/',
'only_create'=>'MRG_MyISAM MERGE HEAP MEMORY',
'globstat'=>0,
'my_host'=>'',
'my_port'=>'',
'my_user'=>'',
'my_pass'=>'',
'my_comp'=>0,
'my_db'=>'',
'auth'=>'Eleanor_CMS',
'user'=>'',
'pass'=>'',
'confirm'=>'6',
'exitURL'=>'./',
);